package lex

import "github.com/nico/jev-trans/internal/forest"

// The lexicon is a table, not a library. plan.md §25 requires morphological
// decomposition to be attempted before anything else, which is only honest if
// the analyzer actually knows the high-frequency vocabulary of ordinary
// Japanese: pronouns, the full particle set, common nouns, the verb and
// adjective classes, numerals with their counters, and the auxiliaries that
// carry tense, politeness and aspect (plan.md §20 lists exactly those as
// source-specific features English cannot infer).

// Part-of-speech codes used by the table. Keeping them short matters: this
// file is the largest artifact in the package and every saved rune is a line
// the reader has to scan past.
const (
	jaPNoun   = "n"
	jaPProper = "N"
	jaPPron   = "pr"
	jaPVerb   = "v"
	jaPAux    = "x"
	jaPAdj    = "a"
	jaPAdv    = "adv"
	jaPPart   = "q"
	jaPConj   = "c"
	jaPPunct  = "."
	jaPNum    = "#"
	jaPDet    = "d"
	jaPAffix  = "f"
	jaPInterj = "!"
)

var jaPOSCodes = map[string]forest.POS{
	jaPNoun:   forest.POSNoun,
	jaPProper: forest.POSProper,
	jaPPron:   forest.POSPronoun,
	jaPVerb:   forest.POSVerb,
	jaPAux:    forest.POSAux,
	jaPAdj:    forest.POSAdj,
	jaPAdv:    forest.POSAdv,
	jaPPart:   forest.POSParticle,
	jaPConj:   forest.POSConj,
	jaPPunct:  forest.POSPunct,
	jaPNum:    forest.POSNum,
	jaPDet:    forest.POSDet,
	jaPInterj: forest.POSInterj,
	jaPAffix:  forest.POSAffix,
}

// jaEntry is one dictionary record.
//
// base is the dictionary form after de-inflection and lem the semantic lemma;
// both default to the surface. When they differ the analyzer must keep them
// apart: 渡った is base 渡す (lexical identity) and lemma 渡る (the predicate the
// ontology will actually resolve), and てしまう is not "食べ + past" at all.
type jaEntry struct {
	surface string
	pos     string
	base    string
	lem     string
	feats   string // space separated key=value pairs
	rank    int    // >0 marks a non-preferred reading of the same surface
}

// jaLexEntry is a resolved lexicon record with parsed features.
type jaLexEntry struct {
	pos   forest.POS
	base  string
	lem   string
	feats map[string]string
	rank  int
}

// Feature keys the analyzer guarantees to produce. They are the vocabulary
// plan.md §12 and §20 describe for the source side; downstream stages read
// them by name, so the strings are part of the contract.
const (
	jaFtTense      = "tense"
	jaFtPolite     = "polite"
	jaFtNegative   = "negative"
	jaFtAspect     = "aspect"
	jaFtCompletion = "completion"
	jaFtHonorific  = "honorific"
	jaFtHumble     = "humble"
	jaFtCase       = "case"
	jaFtSFP        = "sfp"
	jaFtCopula     = "copula"
	jaFtNumeral    = "numeral"
	jaFtQuantifier = "quantifier"
	jaFtHonorNoun  = "honorific_noun"
	jaFtMood       = "mood"
	jaFtConj       = "conj"
	jaFtConjRule   = "rule"
)

// Tense / politeness / aspect values.
const (
	jaTensePast    = "past"
	jaTensePresent = "present"
	jaTenseFuture  = "future"

	jaPoliteMasu = "masu"
	jaPoliteTei  = "tei"

	jaAspectProgressive = "progressive"
	jaAspectPerfect     = "perfect"
	jaAspectCompletion  = "completion"

	jaCompletionDone = "completed"
)

// Frames tell the parser whether an omitted agent is expected (plan.md §15:
// the zero subject is a first-class object, not a missing field, but only
// verbs that require an agent justify creating one).
const (
	jaFrameIntrans = "intransitive"
	jaFrameTrans   = "transitive"
)

// --- categories -----------------------------------------------------------
//
// Order matters only for readability; lookup is by exact surface.

// Punctuation and symbols are morphemes, not noise: the parser needs the
// sentence boundary to close a clause.
var jaPunctuation = []jaEntry{
	{"。", jaPPunct, "", "", "sentence_end=1", 0},
	{"．", jaPPunct, "", "", "sentence_end=1", 0},
	{"、", jaPPunct, "", "", "comma=1", 0},
	{"，", jaPPunct, "", "", "comma=1", 0},
	{"，", jaPPunct, "", "", "comma=1", 1},
	{"・", jaPPunct, "", "", "", 0},
	{"：", jaPPunct, "", "", "", 0},
	{";", jaPPunct, "", "", "", 0},
	{"；", jaPPunct, "", "", "", 0},
	{"！", jaPPunct, "", "", "", 0},
	{"!", jaPPunct, "", "", "", 0},
	{"？", jaPPunct, "", "", "", 0},
	{"?", jaPPunct, "", "", "", 0},
	{"…", jaPPunct, "", "", "", 0},
	{"‥", jaPPunct, "", "", "", 0},
	{"～", jaPPunct, "", "", "", 0},
	{"〜", jaPPunct, "", "", "", 0},
	{"「", jaPPunct, "", "", "quote=open", 0},
	{"」", jaPPunct, "", "", "quote=close", 0},
	{"『", jaPPunct, "", "", "quote=open", 1},
	{"』", jaPPunct, "", "", "quote=close", 1},
	{"（", jaPPunct, "", "", "", 0},
	{"）", jaPPunct, "", "", "", 0},
	{"(", jaPPunct, "", "", "", 0},
	{")", jaPPunct, "", "", "", 0},
	{"[", jaPPunct, "", "", "", 0},
	{"]", jaPPunct, "", "", "", 0},
	{"《", jaPPunct, "", "", "", 0},
	{"》", jaPPunct, "", "", "", 0},
	{"、", jaPPunct, "", "", "", 1},
}

// Particles: the whole functional set, because plan.md §6 and CONTRACTS require
// に/へ/で/と/から/まで/の/を/が/は to be recovered explicitly.
var jaParticles = []jaEntry{
	{"は", jaPPart, "", "", "case=wa", 0},
	{"が", jaPPart, "", "", "case=ga", 0},
	{"を", jaPPart, "", "", "case=wo", 0},
	{"に", jaPPart, "", "", "case=ni", 0},
	{"で", jaPPart, "", "", "case=de", 0},
	{"と", jaPPart, "", "", "case=to", 0},
	{"の", jaPPart, "", "", "case=no", 0},
	{"へ", jaPPart, "", "", "case=he", 0},
	{"から", jaPPart, "から", "から", "case=kara", 0},
	{"まで", jaPPart, "まで", "まで", "case=made", 0},
	{"も", jaPPart, "", "", "case=mo additive=1", 0},
	{"こそ", jaPPart, "", "", "case=ko emphatic=1", 0},
	{"しか", jaPPart, "", "", "case=shi additive=1", 0},
	{"ずつ", jaPAdv, "", "", "iterative=1", 0},
	{"ばかり", jaPAdv, "", "", "exclusively=1", 0},
	{"だけ", jaPAdv, "", "", "exclusively=1", 0},
	{"ほど", jaPAdv, "", "", "degree=1", 0},
	{"など", jaPAdv, "", "", "exemplify=1", 0},
	{"なり", jaPPart, "", "", "case=nari", 0},
	{"より", jaPPart, "", "", "case=yori comparative=1", 0},
	{"へ", jaPPart, "", "", "case=he", 1},
	{"とか", jaPPart, "", "", "case=to quote=1", 0},
	{"など", jaPPart, "", "", "case=to quote=1", 1},
}

// Sentence-final particles carry speaker attitude. plan.md §20 keeps them
// because English has no morpheme for them, so the loss vector has to see them.
var jaSFP = []jaEntry{
	{"ね", jaPPart, "", "", "sfp=ne agreement=1", 0},
	{"よ", jaPPart, "", "", "sfp=yo informative=1", 0},
	{"ぞ", jaPPart, "", "", "sfp=zo emphatic=1", 0},
	{"ぜ", jaPPart, "", "", "sfp=ze emphatic=1", 0},
	{"わ", jaPPart, "", "", "sfp=wa exclamative=1", 0},
	{"な", jaPPart, "", "", "sfp=na negative=1", 1},
	{"かな", jaPAux, "", "", "sfp=kana mood=question", 0},
	{"か", jaPPart, "", "", "sfp=ka mood=question", 0},
	{"か", jaPPart, "", "", "case=ka mood=question", 1},
	{"/", jaPPunct, "", "", "", 0},
}

// Conjunctions and subordinators. conj carries the syntax.Conjoin label the
// parser assigns, so the split into clauses needs no second table.
var jaConjunctions = []jaEntry{
	{"そして", jaPConj, "", "", "conj=AND", 0},
	{"それから", jaPConj, "", "", "conj=AND", 0},
	{"また", jaPAdv, "", "", "conj=AND additive=1", 0},
	{"しかも", jaPConj, "", "", "conj=AND", 0},
	{"さらに", jaPAdv, "", "", "conj=AND", 0},
	{"けれど", jaPConj, "", "", "conj=BUT", 0},
	{"けれども", jaPConj, "", "", "conj=BUT", 0},
	{"けど", jaPConj, "", "", "conj=BUT", 0},
	{"けれども", jaPConj, "", "", "conj=BUT", 1},
	{"が", jaPConj, "", "", "conj=BUT", 1},
	{"のに", jaPConj, "", "", "conj=CONCESSION", 0},
	{"ながら", jaPConj, "", "", "conj=AND", 0},
	{"ので", jaPConj, "", "", "conj=BECAUSE", 0},
	{"から", jaPConj, "", "", "conj=BECAUSE", 0},
	{"ば", jaPConj, "", "", "conj=CONDITION", 0},
	{"たら", jaPConj, "", "", "conj=CONDITION", 0},
	{"なら", jaPConj, "", "", "conj=CONDITION", 0},
	{"なら", jaPConj, "", "", "conj=CONDITION", 1},
	{"とき", jaPConj, "", "", "conj=TEMPORAL_WHEN", 0},
	{"時", jaPConj, "", "", "conj=TEMPORAL_WHEN", 0},
	{"とき", jaPConj, "", "", "conj=TEMPORAL_WHEN", 1},
	{"前", jaPNoun, "", "", "conj=TEMPORAL_BEFORE", 0},
	{"後", jaPNoun, "", "", "conj=TEMPORAL_AFTER", 0},
	{"あと", jaPNoun, "", "", "conj=TEMPORAL_AFTER", 0},
	{"ために", jaPConj, "", "", "conj=PURPOSE", 0},
	{"ため", jaPNoun, "", "", "conj=PURPOSE", 0},
	{"ように", jaPConj, "", "", "conj=PURPOSE", 0},
	{"ように", jaPConj, "", "", "conj=RESULT", 1},
	{"そう", jaPAux, "", "", "evidential=1 conj=RESULT", 0},
	{"だから", jaPConj, "", "", "conj=BECAUSE", 0},
	{"もし", jaPAdv, "", "", "conditional=1", 0},
	{"または", jaPConj, "", "", "conj=OR", 0},
	{"か", jaPConj, "", "", "conj=OR", 1},
	{"および", jaPConj, "", "", "conj=AND", 0},
	{"乃至", jaPConj, "", "", "", 0},
}

// Pronouns, demonstratives and determiners.
var jaPronouns = []jaEntry{
	{"私", jaPPron, "", "", "person=1 number=sg gender=unspecified", 0},
	{"わたし", jaPPron, "", "", "person=1 number=sg gender=unspecified", 0},
	{"僕", jaPPron, "", "", "person=1 number=sg gender=unspecified", 0},
	{"ぼく", jaPPron, "", "", "person=1 number=sg gender=unspecified", 0},
	{"俺", jaPPron, "", "", "person=1 number=sg gender=unspecified", 0},
	{"おれ", jaPPron, "", "", "person=1 number=sg gender=unspecified", 0},
	{"あたし", jaPPron, "", "", "person=1 number=sg gender=unspecified", 0},
	{"私たち", jaPPron, "私たち", "私たち", "person=1 number=pl", 0},
	{"わたしたち", jaPPron, "私たち", "私たち", "person=1 number=pl", 0},
	{"僕たち", jaPPron, "僕たち", "僕たち", "person=1 number=pl", 0},
	{"俺たち", jaPPron, "俺たち", "俺たち", "person=1 number=pl", 0},
	{"皆", jaPNoun, "皆", "皆", "quantifier=all", 0},
	{"みんな", jaPNoun, "みんな", "みんな", "quantifier=all", 0},
	{"全員", jaPNoun, "全員", "全員", "quantifier=all", 0},
	{"誰も", jaPNoun, "誰も", "誰も", "quantifier=none", 0},
	{"だれも", jaPNoun, "誰も", "誰", "quantifier=none", 0},
	{"いくつか", jaPPron, "いくつか", "いくつか", "quantifier=some", 0},
	{"両方", jaPNoun, "両方", "両方", "quantifier=both", 0},
	{"彼", jaPPron, "", "", "person=3 number=sg gender=unspecified", 0},
	{"彼女", jaPPron, "", "", "person=3 number=sg gender=female", 0},
	{"あの人", jaPPron, "", "", "demonstrative=ano person=3", 0},
	{"あのかた", jaPPron, "", "", "demonstrative=ano person=3", 0},
	{"あの方", jaPPron, "", "", "demonstrative=ano person=3 honorific=1", 0},
	{"あの人", jaPPron, "", "", "demonstrative=ano person=3", 1},
	{"あそこ", jaPPron, "", "", "demonstrative=ano place=1", 0},
	{"ここ", jaPPron, "", "", "demonstrative=kono place=1", 0},
	{"そこ", jaPPron, "", "", "demonstrative=sono place=1", 0},
	{"どこ", jaPPron, "", "", "interrogative=1", 0},
	{"あちら", jaPPron, "", "", "demonstrative=ano place=1", 0},
	{"こちら", jaPPron, "", "", "demonstrative=kono place=1", 0},
	{"そちら", jaPPron, "", "", "demonstrative=sono place=1", 0},
	{"どちら", jaPPron, "", "", "interrogative=1", 0},
	{"これ", jaPPron, "", "", "demonstrative=kono", 0},
	{"それ", jaPPron, "", "", "demonstrative=sono", 0},
	{"あれ", jaPPron, "", "", "demonstrative=ano", 0},
	{"この", jaPDet, "", "", "demonstrative=kono", 0},
	{"その", jaPDet, "", "", "demonstrative=sono", 0},
	{"あの", jaPDet, "", "", "demonstrative=ano", 0},
	{"どの", jaPDet, "", "", "interrogative=1", 0},
	{"どの", jaPDet, "", "", "interrogative=1", 1},
	{"こんな", jaPDet, "", "", "demonstrative=konna", 0},
	{"そんな", jaPDet, "", "", "demonstrative=sonna", 0},
	{"あんな", jaPDet, "", "", "demonstrative=anna", 0},
	{"どんな", jaPDet, "", "", "interrogative=1", 0},
	{"あれ", jaPPron, "", "", "demonstrative=ano", 1},
	{"これ", jaPPron, "", "", "demonstrative=kono", 1},
	{"それ", jaPPron, "", "", "demonstrative=sono", 1},
	{"誰", jaPPron, "", "", "person=unspecified", 0},
	{"だれ", jaPPron, "", "", "person=unspecified", 0},
	{"何", jaPPron, "", "", "interrogative=1", 0},
	{"なに", jaPPron, "", "", "interrogative=1", 0},
	{"何", jaPPron, "", "", "interrogative=1", 1},
	{"ひとり", jaPPron, "", "", "number=1 person=unspecified", 0},
	{"ふたり", jaPPron, "", "", "number=2 person=unspecified", 0},
	{"二人", jaPPron, "二人", "二人", "number=2 person=unspecified", 0},
	{"一人", jaPPron, "一人", "一人", "number=1 person=unspecified", 0},
	{"あなた", jaPPron, "", "", "person=2", 0},
	{"貴方", jaPPron, "", "", "person=2 honorific=1", 0},
	{"人", jaPNoun, "", "", "", 0},
	{"人", jaPNoun, "", "", "quantifier=counter counter=people", 1},
	{"方", jaPNoun, "", "", "honorific_noun=respectful", 0},
	{"人達", jaPNoun, "", "", "", 0},
}

// General nouns: the vocabulary any ordinary Japanese sentence leans on.
var jaNouns = []jaEntry{
	{"家", jaPNoun, "", "", "", 0},
	{"会社", jaPNoun, "", "", "organization=1", 0},
	{"学校", jaPNoun, "", "", "place=1 institution=1", 0},
	{"大学", jaPNoun, "", "", "place=1 institution=1", 0},
	{"高校", jaPNoun, "", "", "place=1 institution=1", 0},
	{"中学", jaPNoun, "", "", "place=1 institution=1", 0},
	{"小学校", jaPNoun, "", "", "place=1 institution=1", 0},
	{"病院", jaPNoun, "", "", "place=1 institution=1", 0},
	{"銀行", jaPNoun, "", "", "place=1 institution=1", 0},
	{"郵便局", jaPNoun, "", "", "place=1 institution=1", 0},
	{"図書館", jaPNoun, "", "", "place=1 institution=1", 0},
	{"美術館", jaPNoun, "", "", "place=1", 0},
	{"公園", jaPNoun, "", "", "place=1", 0},
	{"空港", jaPNoun, "", "", "place=1", 0},
	{"駅", jaPNoun, "", "", "place=1", 0},
	{"店", jaPNoun, "", "", "place=1", 0},
	{"部屋", jaPNoun, "", "", "place=1", 0},
	{"教室", jaPNoun, "", "", "place=1", 0},
	{"仕事", jaPNoun, "", "", "", 0},
	{"会議", jaPNoun, "", "", "", 0},
	{"予定", jaPNoun, "", "", "", 0},
	{"計画", jaPNoun, "", "", "", 0},
	{"結果", jaPNoun, "", "", "", 0},
	{"理由", jaPNoun, "", "", "", 0},
	{"説明", jaPNoun, "", "", "", 0},
	{"意味", jaPNoun, "", "", "", 0},
	{"言葉", jaPNoun, "", "", "", 0},
	{"文章", jaPNoun, "", "", "", 0},
	{"問題", jaPNoun, "", "", "", 0},
	{"質問", jaPNoun, "", "", "", 0},
	{"答え", jaPNoun, "", "", "", 0},
	{"情報", jaPNoun, "", "", "", 0},
	{"名前", jaPNoun, "", "", "", 0},
	{"住所", jaPNoun, "", "", "", 0},
	{"電話", jaPNoun, "", "", "", 0},
	{"番号", jaPNoun, "", "", "", 0},
	{"誕生日", jaPNoun, "", "", "", 0},
	{"趣味", jaPNoun, "", "", "", 0},
	{"性格", jaPNoun, "", "", "", 0},
	{"時間", jaPNoun, "", "", "", 0},
	{"毎日", jaPNoun, "", "", "frequency=daily", 0},
	{"毎年", jaPNoun, "", "", "frequency=yearly", 0},
	{"今", jaPNoun, "", "", "deictic=now", 0},
	{"今日", jaPNoun, "", "", "deictic=now", 0},
	{"明日", jaPNoun, "", "", "deictic=future", 0},
	{"昨日", jaPNoun, "", "", "deictic=past", 0},
	{"今朝", jaPNoun, "", "", "deictic=now", 0},
	{"今夜", jaPNoun, "", "", "deictic=now", 0},
	{"去年", jaPNoun, "", "", "deictic=past", 0},
	{"来年", jaPNoun, "", "", "deictic=future", 0},
	{"先月", jaPNoun, "", "", "deictic=past", 0},
	{"来週", jaPNoun, "", "", "deictic=future", 0},
	{"先週", jaPNoun, "", "", "deictic=past", 0},
	{"朝", jaPNoun, "", "", "deictic=morning", 0},
	{"夜", jaPNoun, "", "", "deictic=night", 0},
	{"昼", jaPNoun, "", "", "deictic=noon", 0},
	{"午前", jaPNoun, "", "", "deictic=am", 0},
	{"午後", jaPNoun, "", "", "deictic=pm", 0},
	{"今", jaPAdv, "", "", "time=now", 1},
	{"分", jaPNoun, "", "", "quantifier=counter counter=minute", 0},
	{"時", jaPNoun, "", "", "quantifier=counter counter=hour", 0},
	{"日", jaPNoun, "", "", "quantifier=counter counter=day", 0},
	{"月", jaPNoun, "", "", "quantifier=counter counter=month", 0},
	{"年", jaPNoun, "", "", "quantifier=counter counter=year", 0},
	{"曜日", jaPNoun, "", "", "", 0},
	{"本", jaPNoun, "", "", "", 0},
	{"本", jaPNoun, "", "", "quantifier=counter counter=long_object", 1},
	{"魚", jaPNoun, "", "", "", 0},
	{"肉", jaPNoun, "", "", "", 0},
	{"米", jaPNoun, "", "", "", 0},
	{"野菜", jaPNoun, "", "", "", 0},
	{"果物", jaPNoun, "", "", "", 0},
	{"水", jaPNoun, "", "", "", 0},
	{"お茶", jaPNoun, "", "", "", 0},
	{"茶", jaPNoun, "", "", "", 0},
	{"酒", jaPNoun, "", "", "", 0},
	{"ご飯", jaPNoun, "", "", "", 0},
	{"朝ご飯", jaPNoun, "", "", "", 0},
	{"昼ご飯", jaPNoun, "", "", "", 0},
	{"晩ご飯", jaPNoun, "", "", "", 0},
	{"料理", jaPNoun, "", "", "", 0},
	{"食べ物", jaPNoun, "", "", "", 0},
	{"飲み物", jaPNoun, "", "", "", 0},
	{"車", jaPNoun, "", "", "", 0},
	{"電車", jaPNoun, "", "", "", 0},
	{"バス", jaPNoun, "", "", "", 0},
	{"飛行機", jaPNoun, "", "", "", 0},
	{"自転車", jaPNoun, "", "", "", 0},
	{"地下鉄", jaPNoun, "", "", "", 0},
	{"道", jaPNoun, "", "", "", 0},
	{"道路", jaPNoun, "", "", "", 0},
	{"橋", jaPNoun, "", "", "", 0},
	{"時計", jaPNoun, "", "", "", 0},
	{"携帯", jaPNoun, "", "", "", 0},
	{"携帯電話", jaPNoun, "", "", "", 0},
	{"パソコン", jaPNoun, "", "", "", 0},
	{"テレビ", jaPNoun, "", "", "", 0},
	{"ラジオ", jaPNoun, "", "", "", 0},
	{"新聞", jaPNoun, "", "", "", 0},
	{"雑誌", jaPNoun, "", "", "", 0},
	{"辞書", jaPNoun, "", "", "", 0},
	{"漫画", jaPNoun, "", "", "", 0},
	{"写真", jaPNoun, "", "", "", 0},
	{"絵", jaPNoun, "", "", "", 0},
	{"音楽", jaPNoun, "", "", "", 0},
	{"歌", jaPNoun, "", "", "", 0},
	{"映画", jaPNoun, "", "", "", 0},
	{"ゲーム", jaPNoun, "", "", "", 0},
	{"スポーツ", jaPNoun, "", "", "", 0},
	{"野球", jaPNoun, "", "", "", 0},
	{"サッカー", jaPNoun, "", "", "", 0},
	{"テニス", jaPNoun, "", "", "", 0},
	{"ニュース", jaPNoun, "", "", "", 0},
	{"ノート", jaPNoun, "", "", "", 0},
	{"ペン", jaPNoun, "", "", "", 0},
	{"レストラン", jaPNoun, "", "", "", 0},
	{"事務所", jaPNoun, "", "", "", 0},
	{"体育", jaPNoun, "", "", "", 0},
	{"内容", jaPNoun, "", "", "", 0},
	{"切符", jaPNoun, "", "", "", 0},
	{"判断", jaPNoun, "", "", "", 0},
	{"制約", jaPNoun, "", "", "", 0},
	{"動物", jaPNoun, "", "", "", 0},
	{"友", jaPNoun, "", "", "", 0},
	{"口", jaPNoun, "", "", "", 0},
	{"同僚", jaPNoun, "", "", "", 0},
	{"味", jaPNoun, "", "", "", 0},
	{"地図", jaPNoun, "", "", "", 0},
	{"場合", jaPNoun, "", "", "", 0},
	{"塩", jaPNoun, "", "", "", 0},
	{"夢", jaPNoun, "", "", "", 0},
	{"太陽", jaPNoun, "", "", "", 0},
	{"子ども", jaPNoun, "", "", "", 0},
	{"子供", jaPNoun, "", "", "", 0},
	{"季節", jaPNoun, "", "", "", 0},
	{"実装", jaPNoun, "", "", "", 0},
	{"客", jaPNoun, "", "", "", 0},
	{"将来", jaPNoun, "", "", "", 0},
	{"希望", jaPNoun, "", "", "", 0},
	{"庭", jaPNoun, "", "", "", 0},
	{"式典", jaPNoun, "", "", "", 0},
	{"扉", jaPNoun, "", "", "", 0},
	{"手紙", jaPNoun, "", "", "", 0},
	{"推論", jaPNoun, "", "", "", 0},
	{"教授", jaPNoun, "", "", "", 0},
	{"文法", jaPNoun, "", "", "", 0},
	{"料金", jaPNoun, "", "", "", 0},
	{"方法", jaPNoun, "", "", "", 0},
	{"旅", jaPNoun, "", "", "", 0},
	{"昔", jaPNoun, "", "", "", 0},
	{"服", jaPNoun, "", "", "", 0},
	{"机", jaPNoun, "", "", "", 0},
	{"椅子", jaPNoun, "", "", "", 0},
	{"検証", jaPNoun, "", "", "", 0},
	{"機械", jaPNoun, "", "", "", 0},
	{"気持ち", jaPNoun, "", "", "", 0},
	{"牛", jaPNoun, "", "", "", 0},
	{"状態", jaPNoun, "", "", "", 0},
	{"目的", jaPNoun, "", "", "", 0},
	{"眼鏡", jaPNoun, "", "", "", 0},
	{"砂糖", jaPNoun, "", "", "", 0},
	{"窓", jaPNoun, "", "", "", 0},
	{"箱", jaPNoun, "", "", "", 0},
	{"紙", jaPNoun, "", "", "", 0},
	{"翻訳", jaPNoun, "", "", "", 0},
	{"船", jaPNoun, "", "", "", 0},
	{"街", jaPNoun, "", "", "", 0},
	{"袋", jaPNoun, "", "", "", 0},
	{"規則", jaPNoun, "", "", "", 0},
	{"設計", jaPNoun, "", "", "", 0},
	{"週", jaPNoun, "", "", "", 0},
	{"鍵", jaPNoun, "", "", "", 0},
	{"靴", jaPNoun, "", "", "", 0},
	{"鞄", jaPNoun, "", "", "", 0},
	{"音楽会", jaPNoun, "", "", "", 0},
	{"馬", jaPNoun, "", "", "", 0},
	{"髪", jaPNoun, "", "", "", 0},
	// Everyday katakana loanwords. Without them the analyzer can only offer
	// them as one big UNKNOWN span, which is honest but far less useful: a
	// loanword the tables know is a noun should be segmented as a noun.
	{"ビール", jaPNoun, "", "", "", 0},
	{"コーヒー", jaPNoun, "", "", "", 0},
	{"お茶", jaPNoun, "", "", "", 0},
	{"カメラ", jaPNoun, "", "", "", 0},
	{"テーブル", jaPNoun, "", "", "", 0},
	{"ナイフ", jaPNoun, "", "", "", 0},
	{"フォーク", jaPNoun, "", "", "", 0},
	{"スプーン", jaPNoun, "", "", "", 0},
	{"皿", jaPNoun, "", "", "", 0},
	{"カップ", jaPNoun, "", "", "", 0},
	{"パン", jaPNoun, "", "", "", 0},
	{"ご飯", jaPNoun, "", "", "", 0},
	{"天気", jaPNoun, "", "", "", 0},
	{"雨", jaPNoun, "", "", "", 0},
	{"雪", jaPNoun, "", "", "", 0},
	{"風", jaPNoun, "", "", "", 0},
	{"空", jaPNoun, "", "", "", 0},
	{"海", jaPNoun, "", "", "place=1", 0},
	{"山", jaPNoun, "", "", "place=1", 0},
	{"川", jaPNoun, "", "", "place=1", 0},
	{"花", jaPNoun, "", "", "", 0},
	{"木", jaPNoun, "", "", "", 0},
	{"犬", jaPNoun, "", "", "animate=1", 0},
	{"猫", jaPNoun, "", "", "animate=1", 0},
	{"鳥", jaPNoun, "", "", "animate=1", 0},
	{"虫", jaPNoun, "", "", "animate=1", 0},
	{"魚", jaPNoun, "", "", "animate=1", 1},
	{"目", jaPNoun, "", "", "", 0},
	{"耳", jaPNoun, "", "", "", 0},
	{"手", jaPNoun, "", "", "", 0},
	{"足", jaPNoun, "", "", "", 0},
	{"頭", jaPNoun, "", "", "", 0},
	{"心", jaPNoun, "", "", "", 0},
	{"体", jaPNoun, "", "", "", 0},
	{"顔", jaPNoun, "", "", "", 0},
	{"声", jaPNoun, "", "", "", 0},
	{"力", jaPNoun, "", "", "", 0},
	{"健康", jaPNoun, "", "", "", 0},
	{"病気", jaPNoun, "", "", "", 0},
	{"薬", jaPNoun, "", "", "", 0},
	{"医者", jaPNoun, "", "", "", 0},
	{"研究者", jaPNoun, "", "", "", 0},
	{"漫画家", jaPNoun, "", "", "", 0},
	{"記者", jaPNoun, "", "", "", 0},
	{"警察官", jaPNoun, "", "", "", 0},
	{"看護師", jaPNoun, "", "", "", 0},
	{"制度", jaPNoun, "", "", "", 0},
	{"法律", jaPNoun, "", "", "", 0},
	{"政治", jaPNoun, "", "", "", 0},
	{"経済", jaPNoun, "", "", "", 0},
	{"社会", jaPNoun, "", "", "", 0},
	{"文化", jaPNoun, "", "", "", 0},
	{"技術", jaPNoun, "", "", "", 0},
	{"科学", jaPNoun, "", "", "", 0},
	{"歴史", jaPNoun, "", "", "", 0},
	{"数学", jaPNoun, "", "", "", 0},
	{"言語", jaPNoun, "", "", "", 0},
	{"日本語", jaPNoun, "", "", "language=ja", 0},
	{"英語", jaPNoun, "", "", "language=en", 0},
	{"中国語", jaPNoun, "", "", "language=zh", 0},
	{"韓国語", jaPNoun, "", "", "language=ko", 0},
	{"お金", jaPNoun, "", "", "", 0},
	{"円", jaPNoun, "", "", "currency=JPY", 0},
	{"ドル", jaPNoun, "", "", "currency=USD", 0},
	{"本", jaPNoun, "", "", "quantifier=counter counter=book", 2},
	{"冊", jaPNoun, "", "", "quantifier=counter counter=book", 0},
	{"枚", jaPNoun, "", "", "quantifier=counter counter=flat", 0},
	{"匹", jaPNoun, "", "", "quantifier=counter counter=animal", 0},
	{"頭", jaPNoun, "", "", "quantifier=counter counter=animal_big", 0},
	{"羽", jaPNoun, "", "", "quantifier=counter counter=bird", 0},
	{"個", jaPNoun, "", "", "quantifier=counter counter=generic", 0},
	{"回", jaPNoun, "", "", "quantifier=counter counter=times", 0},
	{"番", jaPNoun, "", "", "quantifier=counter counter=number", 0},
	{"度", jaPNoun, "", "", "quantifier=counter counter=degree", 0},
	{"階", jaPNoun, "", "", "quantifier=counter counter=floor", 0},
	{"台", jaPNoun, "", "", "quantifier=counter counter=machine", 0},
	{"杯", jaPNoun, "", "", "quantifier=counter counter=cup", 0},
	{"組", jaPNoun, "", "", "quantifier=counter counter=set", 0},
	{"軒", jaPNoun, "", "", "quantifier=counter counter=shop", 0},
	{"本", jaPNoun, "", "", "quantifier=counter counter=long_object", 3},
	{"束", jaPNoun, "", "", "quantifier=counter counter=bundle", 0},
	{"艘", jaPNoun, "", "", "quantifier=counter counter=ship", 0},
	{"着", jaPNoun, "", "", "quantifier=counter counter=wear", 0},
	{"デザイン", jaPNoun, "", "", "", 0},
	{"データ", jaPNoun, "", "", "", 0},
	{"プログラム", jaPNoun, "", "", "", 0},
	{"コード", jaPNoun, "", "", "", 0},
	{"テスト", jaPNoun, "", "", "", 0},
	{"システム", jaPNoun, "", "", "", 0},
	{"サービス", jaPNoun, "", "", "", 0},
	{"サイト", jaPNoun, "", "", "", 0},
	{"アカウント", jaPNoun, "", "", "", 0},
	{"ユーザー", jaPNoun, "", "", "", 0},
	{"グループ", jaPNoun, "", "", "", 0},
	{"チーム", jaPNoun, "", "", "", 0},
	{"プロジェクト", jaPNoun, "", "", "", 0},
	{"レポート", jaPNoun, "", "", "", 0},
	{"新聞", jaPNoun, "", "", "", 1},
	{"朝", jaPNoun, "", "", "deictic=morning", 1},
	{"秋", jaPNoun, "", "", "season=autumn", 0},
	{"春", jaPNoun, "", "", "season=spring", 0},
	{"夏", jaPNoun, "", "", "season=summer", 0},
	{"冬", jaPNoun, "", "", "season=winter", 0},
	{"週末", jaPNoun, "", "", "", 0},
	{"毎日", jaPNoun, "", "", "frequency=daily", 1},
	{"世界", jaPNoun, "", "", "place=1", 0},
	{"国", jaPNoun, "", "", "place=1", 0},
	{"町", jaPNoun, "", "", "place=1", 0},
	{"村", jaPNoun, "", "", "place=1", 0},
	{"東京", jaPProper, "", "", "place=1 proper=1", 0},
	{"京都", jaPProper, "", "", "place=1 proper=1", 0},
	{"大阪", jaPProper, "", "", "place=1 proper=1", 0},
	{"名古屋", jaPProper, "", "", "place=1 proper=1", 0},
	{"札幌", jaPProper, "", "", "place=1 proper=1", 0},
	{"福岡", jaPProper, "", "", "place=1 proper=1", 0},
	{"横浜", jaPProper, "", "", "place=1 proper=1", 0},
	{"神戸", jaPProper, "", "", "place=1 proper=1", 0},
	{"広島", jaPProper, "", "", "place=1 proper=1", 0},
	{"仙台", jaPProper, "", "", "place=1 proper=1", 0},
	{"沖縄", jaPProper, "", "", "place=1 proper=1", 0},
	{"北海道", jaPProper, "", "", "place=1 proper=1", 0},
	{"日本", jaPProper, "", "", "place=1 proper=1", 0},
	{"中国", jaPProper, "", "", "place=1 proper=1", 0},
	{"アメリカ", jaPProper, "", "", "place=1 proper=1", 0},
	{"イギリス", jaPProper, "", "", "place=1 proper=1", 0},
	{"韓国", jaPProper, "", "", "place=1 proper=1", 0},
	{"フランス", jaPProper, "", "", "place=1 proper=1", 0},
	{"ドイツ", jaPProper, "", "", "place=1 proper=1", 0},
	{"ロシア", jaPProper, "", "", "place=1 proper=1", 0},
	{"イタリア", jaPProper, "", "", "place=1 proper=1", 0},
	{"スペイン", jaPProper, "", "", "place=1 proper=1", 0},
	{"インド", jaPProper, "", "", "place=1 proper=1", 0},
	{"タイ", jaPProper, "", "", "place=1 proper=1", 0},
	{"太郎", jaPProper, "", "", "proper=1 name_given=1", 0},
	{"次郎", jaPProper, "", "", "proper=1 name_given=1", 0},
	{"花子", jaPProper, "", "", "proper=1 name_given=1", 0},
	{"健太", jaPProper, "", "", "proper=1 name_given=1", 0},
	{"さくら", jaPProper, "", "", "proper=1 name_given=1", 0},
	{"美咲", jaPProper, "", "", "proper=1 name_given=1", 0},
	{"翔太", jaPProper, "", "", "proper=1 name_given=1", 0},
	{"大輔", jaPProper, "", "", "proper=1 name_given=1", 0},
	{"直樹", jaPProper, "", "", "proper=1 name_given=1", 0},
	{"山田", jaPProper, "", "", "proper=1 name_surname=1", 0},
	{"佐藤", jaPProper, "", "", "proper=1 name_surname=1", 0},
	{"鈴木", jaPProper, "", "", "proper=1 name_surname=1", 0},
	{"高橋", jaPProper, "", "", "proper=1 name_surname=1", 0},
	{"田中", jaPProper, "", "", "proper=1 name_surname=1", 0},
	{"伊藤", jaPProper, "", "", "proper=1 name_surname=1", 0},
	{"渡辺", jaPProper, "", "", "proper=1 name_surname=1", 0},
	{"小林", jaPProper, "", "", "proper=1 name_surname=1", 0},
	{"加藤", jaPProper, "", "", "proper=1 name_surname=1", 0},
	{"吉田", jaPProper, "", "", "proper=1 name_surname=1", 0},
	{"松本", jaPProper, "", "", "proper=1 name_surname=1", 0},
	{"井上", jaPProper, "", "", "proper=1 name_surname=1", 0},
	{"木村", jaPProper, "", "", "proper=1 name_surname=1", 0},
	{"林", jaPProper, "", "", "proper=1 name_surname=1", 0},
	{"山口", jaPProper, "", "", "proper=1 name_surname=1", 0},
	{"斎藤", jaPProper, "", "", "proper=1 name_surname=1", 0},
	{"松本", jaPProper, "", "", "proper=1 name_surname=1", 1},
}

// Honorific and kinship nouns. plan.md §5 uses 先生 as the canonical example of
// content English cannot realize, so the noun itself has to carry the register.
var jaHonorificNouns = []jaEntry{
	{"先生", jaPNoun, "", "", "honorific_noun=respectful person=3", 0},
	{"せんせい", jaPNoun, "", "", "honorific_noun=respectful person=3", 0},
	{"社長", jaPNoun, "", "", "honorific_noun=respectful person=3", 0},
	{"部長", jaPNoun, "", "", "honorific_noun=respectful person=3", 0},
	{"課長", jaPNoun, "", "", "honorific_noun=respectful person=3", 0},
	{"係長", jaPNoun, "", "", "honorific_noun=respectful person=3", 0},
	{"主任", jaPNoun, "", "", "honorific_noun=respectful person=3", 0},
	{"先輩", jaPNoun, "", "", "honorific_noun=respectful person=3", 0},
	{"後輩", jaPNoun, "", "", "", 0},
	{"王様", jaPNoun, "", "", "honorific_noun=respectful person=3", 0},
	{"天皇", jaPNoun, "", "", "honorific_noun=respectful person=3", 0},
	{"陛下", jaPNoun, "", "", "honorific_noun=respectful person=3", 0},
	{"お父さん", jaPNoun, "", "", "honorific_noun=respectful kinship=father", 0},
	{"お母さん", jaPNoun, "", "", "honorific_noun=respectful kinship=mother", 0},
	{"お兄さん", jaPNoun, "", "", "honorific_noun=respectful kinship=elder_brother", 0},
	{"お姉さん", jaPNoun, "", "", "honorific_noun=respectful kinship=elder_sister", 0},
	{"お兄ちゃん", jaPNoun, "", "", "honorific_noun=respectful kinship=elder_brother", 0},
	{"お姉ちゃん", jaPNoun, "", "", "honorific_noun=respectful kinship=elder_sister", 0},
	{"おじいさん", jaPNoun, "", "", "honorific_noun=respectful kinship=grandfather", 0},
	{"おばあさん", jaPNoun, "", "", "honorific_noun=respectful kinship=grandmother", 0},
	{"父", jaPNoun, "", "", "kinship=father", 0},
	{"母", jaPNoun, "", "", "kinship=mother", 0},
	{"姉", jaPNoun, "", "", "kinship=elder_sister", 0},
	{"兄", jaPNoun, "", "", "kinship=elder_brother", 0},
	{"妹", jaPNoun, "", "", "kinship=younger_sister", 0},
	{"弟", jaPNoun, "", "", "kinship=younger_brother", 0},
	{"家族", jaPNoun, "", "", "", 0},
	{"友達", jaPNoun, "", "", "", 0},
	{"仲間", jaPNoun, "", "", "", 0},
	{"隣人", jaPNoun, "", "", "", 0},
	{"学生", jaPNoun, "", "", "person=3 role=student", 0},
	{"生徒", jaPNoun, "", "", "person=3 role=student", 0},
	{"留学生", jaPNoun, "", "", "person=3 role=student", 0},
	{"小学生", jaPNoun, "", "", "person=3 role=student", 0},
	{"中学生", jaPNoun, "", "", "person=3 role=student", 0},
	{"大学生", jaPNoun, "", "", "person=3 role=student", 0},
	{"社員", jaPNoun, "", "", "person=3 role=employee", 0},
	{"職業", jaPNoun, "", "", "", 0},
	{"名前", jaPNoun, "", "", "", 1},
	{"さん", jaPNoun, "", "", "honorific_noun=respectful honorific_suffix=1", 0},
	{"君", jaPNoun, "", "", "honorific_noun=respectful honorific_suffix=1", 0},
	{"ちゃん", jaPNoun, "", "", "honorific_noun=respectful honorific_suffix=1", 0},
	{"様", jaPNoun, "", "", "honorific_noun=respectful honorific_suffix=1", 0},
}

// Adjectives. Both classes are listed because plan.md §25 requires
// morphological decomposition to keep the distinction the projection stage
// needs (する + な-adjective vs. plain -い).
var jaAdjectivesI = []jaEntry{
	{"高い", jaPAdj, "", "", "adj=i", 0},
	{"低い", jaPAdj, "", "", "adj=i", 0},
	{"大きい", jaPAdj, "", "", "adj=i", 0},
	{"小さい", jaPAdj, "", "", "adj=i", 0},
	{"新しい", jaPAdj, "", "", "adj=i", 0},
	{"古い", jaPAdj, "", "", "adj=i", 0},
	{"良い", jaPAdj, "", "", "adj=i", 0},
	{"いい", jaPAdj, "良い", "良い", "adj=i", 0},
	{"悪い", jaPAdj, "", "", "adj=i", 0},
	{"美しい", jaPAdj, "", "", "adj=i", 0},
	{"漂亮", jaPAdj, "", "", "adj=i", 0},
	{"長い", jaPAdj, "", "", "adj=i", 0},
	{"短い", jaPAdj, "", "", "adj=i", 0},
	{"早い", jaPAdj, "", "", "adj=i", 0},
	{"速い", jaPAdj, "", "", "adj=i", 0},
	{"遅い", jaPAdj, "", "", "adj=i", 0},
	{"強い", jaPAdj, "", "", "adj=i", 0},
	{"弱い", jaPAdj, "", "", "adj=i", 0},
	{"暑い", jaPAdj, "", "", "adj=i", 0},
	{"寒い", jaPAdj, "", "", "adj=i", 0},
	{"熱い", jaPAdj, "", "", "adj=i", 0},
	{"冷たい", jaPAdj, "", "", "adj=i", 0},
	{"甘い", jaPAdj, "", "", "adj=i", 0},
	{"辛い", jaPAdj, "", "", "adj=i", 0},
	{"苦い", jaPAdj, "", "", "adj=i", 0},
	{"美味しい", jaPAdj, "", "", "adj=i", 0},
	{"うまい", jaPAdj, "", "", "adj=i", 0},
	{"美味しい", jaPAdj, "", "", "adj=i evaluative=positive", 1},
	{"楽しい", jaPAdj, "", "", "adj=i evaluative=positive", 0},
	{"面白い", jaPAdj, "", "", "adj=i evaluative=positive", 0},
	{"悲しい", jaPAdj, "", "", "adj=i evaluative=negative", 0},
	{"嬉しい", jaPAdj, "", "", "adj=i evaluative=positive", 0},
	{"楽しい", jaPAdj, "", "", "adj=i", 1},
	{"怖い", jaPAdj, "", "", "adj=i", 0},
	{"遠い", jaPAdj, "", "", "adj=i", 0},
	{"近い", jaPAdj, "", "", "adj=i", 0},
	{"少ない", jaPAdj, "", "", "adj=i", 0},
	{"多い", jaPAdj, "", "", "adj=i", 0},
	{"白い", jaPAdj, "", "", "adj=i", 0},
	{"黒い", jaPAdj, "", "", "adj=i", 0},
	{"赤い", jaPAdj, "", "", "adj=i", 0},
	{"青い", jaPAdj, "", "", "adj=i", 0},
	{"黄色い", jaPAdj, "", "", "adj=i", 0},
	{"明るい", jaPAdj, "", "", "adj=i", 0},
	{"暗い", jaPAdj, "", "", "adj=i", 0},
	{"広い", jaPAdj, "", "", "adj=i", 0},
	{"狭い", jaPAdj, "", "", "adj=i", 0},
	{"重い", jaPAdj, "", "", "adj=i", 0},
	{"軽い", jaPAdj, "", "", "adj=i", 0},
	{"若い", jaPAdj, "", "", "adj=i", 0},
	{"難しい", jaPAdj, "", "", "adj=i", 0},
	{"易しい", jaPAdj, "", "", "adj=i", 0},
	{"正しい", jaPAdj, "", "", "adj=i", 0},
	{"好き", jaPAdj, "好き", "好き", "adj=na evaluative=positive", 0},
	{"嫌い", jaPAdj, "嫌い", "嫌い", "adj=na evaluative=negative", 0},
	{"上手", jaPAdj, "上手", "上手", "adj=na evaluative=positive", 0},
	{"下手", jaPAdj, "下手", "下手", "adj=na evaluative=negative", 0},
	{"元気", jaPAdj, "元気", "元気", "adj=na", 0},
	{"静か", jaPAdj, "静か", "静か", "adj=na", 0},
	{"賑やか", jaPAdj, "賑やか", "賑やか", "adj=na", 0},
	{"綺麗", jaPAdj, "綺麗", "綺麗", "adj=na", 0},
	{"きれい", jaPAdj, "綺麗", "綺麗", "adj=na", 0},
	{"健康", jaPAdj, "健康", "健康", "adj=na", 0},
	{"安全", jaPAdj, "安全", "安全", "adj=na", 0},
	{"危険", jaPAdj, "危険", "危険", "adj=na", 0},
	{"大切", jaPAdj, "大切", "大切", "adj=na", 0},
	{"丁寧", jaPAdj, "丁寧", "丁寧", "adj=na", 0},
	{"簡単", jaPAdj, "簡単", "簡単", "adj=na", 0},
	{"複雑", jaPAdj, "複雑", "複雑", "adj=na", 0},
	{"普通", jaPAdj, "普通", "普通", "adj=na", 0},
	{"特別", jaPAdj, "特別", "特別", "adj=na", 0},
	{"有名", jaPAdj, "有名", "有名", "adj=na", 0},
	{"便利", jaPAdj, "便利", "便利", "adj=na", 0},
	{"不便", jaPAdj, "不便", "不便", "adj=na", 0},
	{"無理", jaPAdj, "無理", "無理", "adj=na", 0},
	{"必要", jaPAdj, "必要", "必要", "adj=na", 0},
	{"重要", jaPAdj, "重要", "重要", "adj=na", 0},
	{"本当", jaPAdj, "本当", "本当", "adj=na", 0},
	{"正規", jaPAdj, "正規", "正規", "adj=na", 0},
}

// Adverbs.
var jaAdverbs = []jaEntry{
	{"とても", jaPAdv, "", "", "degree=strong", 0},
	{"超", jaPAdv, "", "", "degree=strong", 0},
	{"ちょっと", jaPAdv, "", "", "degree=slight", 0},
	{"少し", jaPAdv, "", "", "degree=slight", 0},
	{"たくさん", jaPAdv, "", "", "degree=many", 0},
	{"あまり", jaPAdv, "", "", "degree=negative", 0},
	{"全然", jaPAdv, "", "", "degree=negative", 0},
	{"全く", jaPAdv, "", "", "degree=negative", 0},
	{"必ず", jaPAdv, "", "", "modality=obligatory", 0},
	{"きっと", jaPAdv, "", "", "modality=presumptive", 0},
	{"たぶん", jaPAdv, "", "", "modality=presumptive evidential=1", 0},
	{"きっと", jaPAdv, "", "", "modality=presumptive evidential=1", 1},
	{"よく", jaPAdv, "", "", "frequency=often", 0},
	{"時々", jaPAdv, "", "", "frequency=sometimes", 0},
	{"いつも", jaPAdv, "", "", "frequency=always", 0},
	{"常に", jaPAdv, "", "", "frequency=always", 0},
	{"よく", jaPAdv, "", "", "frequency=often", 1},
	{"早く", jaPAdv, "", "", "manner=fast", 0},
	{"速く", jaPAdv, "", "", "manner=fast", 0},
	{"遅く", jaPAdv, "", "", "manner=slow", 0},
	{"すぐ", jaPAdv, "", "", "manner=immediately", 0},
	{"まだ", jaPAdv, "", "", "aspect=progressive", 0},
	{"もう", jaPAdv, "", "", "aspect=completion", 0},
	{"再び", jaPAdv, "", "", "again=1", 0},
	{"もう一度", jaPAdv, "", "", "again=1", 0},
	{"一緒に", jaPAdv, "", "", "comitative=1", 0},
	{"二人で", jaPAdv, "", "", "comitative=1", 0},
	{"个别", jaPAdv, "", "", "", 0},
	{"もちろん", jaPAdv, "", "", "", 0},
	{"特に", jaPAdv, "", "", "focus=1", 0},
	{"実際", jaPAdv, "", "", "evidential=1", 0},
	{"本当に", jaPAdv, "", "", "emphatic=1", 0},
	{"実は", jaPAdv, "", "", "evidential=1", 0},
	{"まず", jaPAdv, "", "", "discourse=first", 0},
	{"最後に", jaPAdv, "", "", "discourse=last", 0},
	{"再び", jaPAdv, "", "", "again=1", 1},
	{"ちょっと", jaPAdv, "", "", "degree=slight", 1},
	{"ついで", jaPAdv, "", "", "", 0},
	{"奬", jaPAdv, "", "", "", 0},
	{"ちゃんと", jaPAdv, "", "", "manner=properly", 0},
	{"ゆっくり", jaPAdv, "", "", "manner=slowly", 0},
	{"すぐ", jaPAdv, "", "", "manner=immediately", 1},
	{"よく", jaPAdv, "", "", "manner=well", 2},
	{"不要", jaPAdv, "", "", "", 0},
}

// Numerals: single kanji digits get their value as a feature, longer runs are
// composed by the analyzer's numeral rule.
var jaNumerals = []jaEntry{
	{"一", jaPNum, "一", "一", "numeral=1", 0},
	{"二", jaPNum, "二", "二", "numeral=2", 0},
	{"三", jaPNum, "三", "三", "numeral=3", 0},
	{"四", jaPNum, "四", "四", "numeral=4", 0},
	{"五", jaPNum, "五", "五", "numeral=5", 0},
	{"六", jaPNum, "六", "六", "numeral=6", 0},
	{"七", jaPNum, "七", "七", "numeral=7", 0},
	{"八", jaPNum, "八", "八", "numeral=8", 0},
	{"九", jaPNum, "九", "九", "numeral=9", 0},
	{"十", jaPNum, "十", "十", "numeral=10", 0},
	{"百", jaPNum, "百", "百", "numeral=100", 0},
	{"千", jaPNum, "千", "千", "numeral=1000", 0},
	{"万", jaPNum, "万", "万", "numeral=10000", 0},
	{"億", jaPNum, "億", "億", "numeral=100000000", 0},
	{"兆", jaPNum, "兆", "兆", "numeral=1000000000000", 0},
	{"零", jaPNum, "零", "零", "numeral=0", 0},
	{"半", jaPNoun, "", "", "numeral=half", 0},
	{"第", jaPDet, "", "", "ordinal=1", 0},
}

// Verbs.
//
// cj records the conjugation class so the de-inflector never has to guess it
// from the okurigana, and frame records whether the verb obliges the parser to
// expect an agent. frame is what turns "no が-phrase" into a first-class zero
// subject instead of a silent gap (plan.md §15).
var jaVerbsGodan = []jaEntry{
	{"追う", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"住む", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"脱ぐ", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"洗う", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"貼る", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"掘る", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"滑る", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"急ぐ", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"弱る", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"省く", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"承知", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"opter", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"書く", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"読む", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"話す", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"話す", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"聞く", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"帰る", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"帰る", jaPVerb, "", "", "cj=g frame=transitive", 1},
	{"取る", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"使う", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"待つ", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"立つ", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"座る", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"死ぬ", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"死ぬ", jaPVerb, "", "", "cj=g frame=transitive", 1},
	{"買う", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"売る", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"選ぶ", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"泳ぐ", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"遊ぶ", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"飲む", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"食う", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"言う", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"問う", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"泣く", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"笑う", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"咲く", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"吹く", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"行く", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"作る", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"撮る", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"描く", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"作る", jaPVerb, "", "", "cj=g frame=transitive", 1},
	{"預ける", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"借りる", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"返す", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"貸す", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"渡す", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"届ける", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"送る", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"あげる", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"もらう", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"呼ぶ", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"走る", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"止まる", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"始まる", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"終わる", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"閉まる", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"分かる", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"分ける", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"決まる", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"喜ぶ", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"生きる", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"育つ", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"酔う", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"痛む", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"動く", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"続く", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"曲がる", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"働く", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"焦る", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"見る", jaPVerb, "", "", "cj=i frame=transitive", 0},
	{"忘れる", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"創る", jaPVerb, "", "", "cj=g frame=transitive", 0},
	{"分かる", jaPVerb, "分かる", "分かる", "cj=g frame=transitive", 1},
}

var jaVerbsIchidan = []jaEntry{
	{"食べる", jaPVerb, "", "", "cj=i frame=transitive", 0},
	{"飲む", jaPVerb, "飲む", "飲む", "cj=g frame=transitive", 1},
	{"見る", jaPVerb, "", "", "cj=i frame=transitive", 1},
	{"教える", jaPVerb, "", "", "cj=i frame=transitive", 0},
	{"出る", jaPVerb, "", "", "cj=i frame=transitive", 0},
	{"入る", jaPVerb, "", "", "cj=i frame=transitive", 0},
	{"得る", jaPVerb, "", "", "cj=i frame=transitive", 0},
	{"開ける", jaPVerb, "", "", "cj=i frame=transitive", 0},
	{"閉める", jaPVerb, "", "", "cj=i frame=transitive", 0},
	{"着る", jaPVerb, "", "", "cj=i frame=transitive", 0},
	{"寝る", jaPVerb, "", "", "cj=i frame=transitive", 0},
	{"逃げる", jaPVerb, "", "", "cj=i frame=transitive", 0},
	{"付ける", jaPVerb, "", "", "cj=i frame=transitive", 0},
	{"生まれる", jaPVerb, "", "", "cj=i frame=transitive", 0},
	{"諦める", jaPVerb, "", "", "cj=i frame=transitive", 0},
	{"決める", jaPVerb, "", "", "cj=i frame=transitive", 0},
	{"伝える", jaPVerb, "", "", "cj=i frame=transitive", 0},
	{"勤める", jaPVerb, "", "", "cj=i frame=transitive", 0},
	{"調べる", jaPVerb, "", "", "cj=i frame=transitive", 0},
	{"認める", jaPVerb, "", "", "cj=i frame=transitive", 0},
	{"答える", jaPVerb, "", "", "cj=i frame=transitive", 0},
	{"数える", jaPVerb, "", "", "cj=i frame=transitive", 0},
	{"増える", jaPVerb, "", "", "cj=i frame=transitive", 0},
	{"減る", jaPVerb, "", "", "cj=i frame=transitive", 0},
	{"疲れる", jaPVerb, "", "", "cj=i frame=transitive", 0},
	{"慣れる", jaPVerb, "", "", "cj=i frame=transitive", 0},
	{"離れる", jaPVerb, "", "", "cj=i frame=transitive", 0},
	{"隠れる", jaPVerb, "", "", "cj=i frame=transitive", 0},
	{"現れる", jaPVerb, "", "", "cj=i frame=transitive", 0},
	{"消える", jaPVerb, "", "", "cj=i frame=transitive", 0},
	{"聞こえる", jaPVerb, "", "", "cj=i frame=transitive", 0},
	{"見える", jaPVerb, "", "", "cj=i frame=transitive", 0},
	{"できる", jaPVerb, "できる", "出来る", "cj=i frame=transitive", 0},
	{"出来る", jaPVerb, "できる", "出来る", "cj=i frame=transitive", 0},
	{"いる", jaPVerb, "", "居る", "cj=i frame=transitive", 0},
	{"居る", jaPVerb, "いる", "居る", "cj=i frame=transitive", 1},
	{"おる", jaPVerb, "", "居る", "cj=i frame=transitive honorific=humble", 0},
	{"いる", jaPAux, "いる", "居る", "aspect=progressive", 1},
	{"おる", jaPAux, "おる", "居る", "aspect=progressive honorific=humble", 1},
	{"要用", jaPVerb, "", "", "cj=i frame=transitive", 0},
	{"揃える", jaPVerb, "", "", "cj=i frame=transitive", 0},
	{"遅れる", jaPVerb, "", "", "cj=i frame=transitive", 0},
	{"知らせる", jaPVerb, "", "", "cj=i frame=transitive", 0},
	{"知らせる", jaPVerb, "", "", "cj=i frame=transitive", 1},
	{"吠える", jaPVerb, "", "", "cj=i frame=transitive", 0},
	{"冷える", jaPVerb, "", "", "cj=i frame=transitive", 0},
	{"始める", jaPVerb, "", "", "cj=i frame=transitive", 0},
	{"足りる", jaPVerb, "", "", "cj=i frame=transitive", 0},
}

// する-class verbs. The bare nouns double as the する stem so 勉強します and
// 勉強analytic する resolve to the same predicate.
var jaVerbsSuru = []jaEntry{
	{"する", jaPVerb, "", "", "cj=s frame=transitive", 0},
	{"致す", jaPVerb, "する", "致す", "cj=s frame=transitive honorific=humble", 0},
	{"いたす", jaPVerb, "する", "致す", "cj=s frame=transitive honorific=humble", 0},
	{"申す", jaPVerb, "する", "申す", "cj=s frame=transitive honorific=humble", 0},
	{"伺う", jaPVerb, "伺う", "伺う", "cj=g frame=transitive honorific=humble", 0},
	{"がある", jaPVerb, "ある", "ある", "cj=g frame=intransitive", 0},
	{"ある", jaPVerb, "", "", "cj=i frame=intransitive", 0},
	{"ない", jaPAux, "ない", "ない", "negative_aux=1", 0},
	{"勉強", jaPNoun, "", "", "suru=1", 0},
	{"学習", jaPNoun, "", "", "suru=1", 0},
	{"研究", jaPNoun, "", "", "suru=1", 0},
	{"説明", jaPNoun, "", "", "suru=1", 0},
	{"質問", jaPNoun, "", "", "suru=1", 0},
	{"計算", jaPNoun, "", "", "suru=1", 0},
	{"準備", jaPNoun, "", "", "suru=1", 0},
	{"約束", jaPNoun, "", "", "suru=1", 0},
	{"連絡", jaPNoun, "", "", "suru=1", 0},
	{"報告", jaPNoun, "", "", "suru=1", 0},
	{"相談", jaPNoun, "", "", "suru=1", 0},
	{"散歩", jaPNoun, "", "", "suru=1", 0},
	{"休憩", jaPNoun, "", "", "suru=1", 0},
	{"通勤", jaPNoun, "", "", "suru=1", 0},
	{"旅行", jaPNoun, "", "", "suru=1", 0},
	{"映画", jaPNoun, "", "", "suru=1", 1},
	{"料理", jaPNoun, "", "", "suru=1", 1},
	{"掃除", jaPNoun, "", "", "suru=1", 0},
	{"洗濯", jaPNoun, "", "", "suru=1", 0},
	{"買い物", jaPNoun, "", "", "suru=1", 0},
	{"練習", jaPNoun, "", "", "suru=1", 0},
	{"試験", jaPNoun, "", "", "suru=1", 0},
	{"会議", jaPNoun, "", "", "suru=1", 1},
	{"案内", jaPNoun, "", "", "suru=1", 0},
	{"心配", jaPNoun, "", "", "suru=1", 0},
	{"失望", jaPNoun, "", "", "suru=1", 0},
	{"成長", jaPNoun, "", "", "suru=1", 0},
	{"出発", jaPNoun, "", "", "suru=1", 0},
	{"到着", jaPNoun, "", "", "suru=1", 0},
	{"利用", jaPNoun, "", "", "suru=1", 0},
	{"参加", jaPNoun, "", "", "suru=1", 0},
	{"出席", jaPNoun, "", "", "suru=1", 0},
	{"専門", jaPNoun, "", "", "", 0},
}

// Copulas: they carry tense and politeness on their own, and the parser reads
// them off the clause, so だ/である must never be merged into the noun.
var jaCopulas = []jaEntry{
	{"だ", jaPAux, "", "", jaFtCopula + "=da tense=" + jaTensePresent + " polite=plain", 0},
	{"である", jaPAux, "", "", jaFtCopula + "=da tense=" + jaTensePresent + " polite=plain formality=formal", 0},
	{"です", jaPAux, "", "", jaFtCopula + "=da tense=" + jaTensePresent + " polite=" + jaPoliteTei, 0},
	{"でした", jaPAux, "", "", jaFtCopula + "=da tense=" + jaTensePast + " polite=" + jaPoliteTei, 0},
	{"だった", jaPAux, "", "", jaFtCopula + "=da tense=" + jaTensePast + " polite=plain", 0},
	{"ですから", jaPConj, "", "", jaFtCopula + "=da polite=" + jaPoliteTei + " conj=BECAUSE", 0},
	{"ですね", jaPAux, "", "", jaFtCopula + "=da polite=" + jaPoliteTei + " sfp=ne agreement=1", 0},
	{"ですか", jaPAux, "", "", jaFtCopula + "=da polite=" + jaPoliteTei + " mood=question", 0},
	{"でした", jaPAux, "", "", jaFtCopula + "=da tense=" + jaTensePast + " polite=" + jaPoliteTei + " mood=question", 1},
	{"だろう", jaPAux, "", "", jaFtCopula + "=da mood=presumptive polite=plain", 0},
	{"でしょう", jaPAux, "", "", jaFtCopula + "=da mood=presumptive polite=" + jaPoliteTei + " sfp=kamoshideshou", 0},
	{"だろう", jaPAux, "", "", jaFtCopula + "=da mood=presumptive polite=" + jaPoliteTei + " sfp=kamoshideshou", 1},
	{"じゃない", jaPAux, "", "", jaFtCopula + "=da negative=1 polite=plain", 0},
	{"ではない", jaPAux, "", "", jaFtCopula + "=da negative=1 polite=plain", 0},
	{"じゃないです", jaPAux, "", "", jaFtCopula + "=da negative=1 polite=" + jaPoliteTei, 0},
	{"ではありません", jaPAux, "", "", jaFtCopula + "=da negative=1 polite=" + jaPoliteTei, 0},
	{"であり", jaPAux, "", "", jaFtCopula + "=da tense=" + jaTensePresent + " polite=plain", 0},
	{"ですか", jaPAux, "", "", jaFtCopula + "=da polite=" + jaPoliteTei + " sfp=ka mood=question", 1},
	{"ません", jaPAux, "ない", "ない", "negative=1 tense=" + jaTensePresent + " polite=" + jaPoliteMasu, 0},
	{"ましょう", jaPAux, "する", "する", "mood=volitional polite=" + jaPoliteMasu, 0},
	{"ませんか", jaPAux, "する", "する", "mood=question_invitation polite=" + jaPoliteMasu, 0},
	{"ましょうか", jaPAux, "する", "する", "mood=presumptive_question polite=" + jaPoliteMasu, 0},
	{"だよね", jaPAux, "", "", jaFtCopula + "=da sfp=ne agreement=1", 0},
}

// Auxiliaries. Roles live here rather than in the de-inflector so that
// てしまう (completion + regret) and ている (progressive) stay separate
// predicates, which is exactly what plan.md §12 refuses to collapse.
var jaAuxiliaries = []jaEntry{
	{"いる", jaPAux, "", "居る", "aspect=" + jaAspectProgressive, 0},
	{"て", jaPAffix, "", "", "conj=te", 0},
	{"で", jaPAffix, "", "", "conj=te", 1},
	{"しまう", jaPAux, "", "しまう", "completion=" + jaCompletionDone + " mood=regret", 0},
	{"しまう", jaPVerb, "", "しまう", "cj=g frame=transitive", 1},
	{"おく", jaPAux, "", "おく", "aspect=" + jaAspectPerfect + " preparatory=1", 0},
	{"おく", jaPVerb, "置く", "置く", "cj=g frame=transitive", 1},
	{"みる", jaPAux, "", "みる", "aspect=tentative", 0},
	{"見る", jaPAux, "", "見る", "aspect=tentative", 2},
	{"見る", jaPVerb, "見る", "見る", "cj=i frame=transitive", 2},
	{"くる", jaPAux, "", "来る", "direction=from_speaker", 0},
	{"くる", jaPVerb, "来る", "来る", "cj=k frame=transitive", 1},
	{"くる", jaPVerb, "来る", "来る", "cj=k frame=transitive", 2},
	{"くれる", jaPAux, "", "くれる", "benefactive=beneficiary", 0},
	{"くれる", jaPVerb, "くれる", "くれる", "cj=i frame=transitive", 1},
	{"もらう", jaPAux, "", "もらう", "benefactive=request", 0},
	{"ください", jaPAux, "くださる", "くださる", "politeness=request honorific=respectful", 0},
	{"くださる", jaPVerb, "", "くださる", "cj=g frame=transitive honorific=respectful", 0},
	{"なさい", jaPAux, "", "なさる", "politeness=command honorific=respectful", 0},
	{"なさる", jaPVerb, "", "なさる", "cj=r frame=transitive honorific=respectful", 0},
	{"いらっしゃる", jaPVerb, "", "いらっしゃる", "cj=r frame=transitive honorific=respectful", 0},
	{"いる", jaPVerb, "いる", "いる", "cj=i frame=transitive honorific=respectful", 2},
	{"ある", jaPAux, "", "ある", "aspect=perfect", 0},
	{"まま", jaPNoun, "", "", "conj=AND", 0},
}

// The te-form connective that heads every auxiliary compound. plan.md §12 needs
// て + いる / て + しまう split into constituents, so these two surfaces are
// never matched as whole morphemes.
var jaTeConnectives = []string{"て", "で"}

// Sentence-final auxiliaries and copula particles that can trail a ている /
// しまう compound; the analyzer splits them off so the question or agreement
// reading survives.
var jaAuxTails = []string{"ませんか", "ましょうか", "ますか", "ですね", "ですか", "ましょう", "ますね"}

// jaNameSuffixes drive the last-resort proper-noun guess for unknown kanji
// compounds. It is marked Unknown and flagged with a note: the system offers the
// reading as a candidate, never as a fact (house rule 1).
var jaNameSuffixes = map[string]string{
	"子": "name_given=1 gender_hint=unspecified",
	"郎": "name_given=1 gender_hint=unspecified",
	"雄": "name_given=1 gender_hint=unspecified",
	"夫": "name_given=1 gender_hint=unspecified",
	"樹": "name_given=1 gender_hint=unspecified",
	"太": "name_given=1 gender_hint=unspecified",
	"花": "name_given=1 gender_hint=unspecified",
	"菜": "name_given=1 gender_hint=unspecified",
	"代": "name_given=1 gender_hint=unspecified",
}

// jaVerbsExtra are high-frequency verbs that keep the analyzer's coverage of
// ordinary prose; they live in their own slice so the main class tables stay
// readable.
var jaVerbsExtra = []jaEntry{
	{"来る", jaPVerb, "", "来る", "cj=k frame=intransitive", 0},
	{"起きる", jaPVerb, "", "起きる", "cj=g frame=intransitive", 0},
	{"持つ", jaPVerb, "", "持つ", "cj=g frame=transitive", 0},
	{"会う", jaPVerb, "", "会う", "cj=g frame=intransitive", 0},
	{"続ける", jaPVerb, "", "続ける", "cj=i frame=transitive", 0},
	{"頑張る", jaPVerb, "", "頑張る", "cj=g frame=intransitive", 0},
	{"基づく", jaPVerb, "", "基づく", "", 0},
	{"降る", jaPVerb, "", "降る", "cj=g frame=intransitive", 0},
	{"止む", jaPVerb, "", "止む", "cj=g frame=intransitive", 0},
	{"休む", jaPVerb, "", "休む", "cj=g frame=transitive", 0},
	{"積もる", jaPVerb, "", "積もる", "cj=g frame=transitive", 0},
	{"晴れる", jaPVerb, "", "晴れる", "cj=i frame=transitive", 0},
	{"曇る", jaPVerb, "", "曇る", "cj=g frame=transitive", 0},
	{"基于", jaPVerb, "", "基づく", "", 0},
	{"上がる", jaPVerb, "", "上がる", "cj=g frame=intransitive", 0},
	{"下がる", jaPVerb, "", "下がる", "cj=g frame=intransitive", 0},
	{"分かる", jaPVerb, "分かる", "分かる", "cj=g frame=intransitive", 0},
	{"できる", jaPVerb, "できる", "出来る", "cj=i frame=intransitive", 1},
}

// jaAll is every category, concatenated once at init.
var jaAll = [][]jaEntry{
	jaPunctuation, jaParticles, jaSFP, jaConjunctions, jaPronouns, jaNouns,
	jaHonorificNouns, jaAdjectivesI, jaAdverbs, jaNumerals, jaVerbsGodan,
	jaVerbsIchidan, jaVerbsSuru, jaCopulas, jaAuxiliaries, jaVerbsExtra,
}
