package lexicon

// Japanese surface data.
//
// Entries are dictionary forms; the conjugation generator in lexicon.go
// derives every inflected form, so a row lists the lemma once. Weight is the
// prior for that reading: it orders candidates and seeds jlir.Distribution,
// but no reading is ever deleted (plan.md §2, §10).
//
// Inflected surfaces are generated by the analyzer's own conjugation tables
// (lex.JAConjugations), so a verb row lists its lemma once. Forms is only for
// the shapes no forward table produces — the te-form that drops a kana
// (疲れて), or an irregular class the analyzer does not model.
//
// A row carrying several senses with comparable weights is the point of the
// whole design: 行く keeps "go" and "attend", 見る keeps "see", "meet" and
// "read", 出す keeps "hand over", "publish" and "take out".

// jaTableA: locomotion and the transfer of a theme.
var jaTableA = []entry{
	// 行く is the classic 五段 exception: its te-form is 行って, not 行いて.
	{Base: "行く", Forms: []string{"行って", "行った", "行ったら", "行ったり", "行ってた"}, Spec: "MOVE.01:0.88 MOVE.04:0.08 WORK.01:0.04"},
	// 来る is irregular: 来て, 来た, 来ない, 来ます.
	{Base: "来る", Forms: []string{"くる", "来て", "来た", "来てた", "来たら", "来ない", "来なかった", "来ます", "来ました", "来ません", "来い"}, Spec: "MOVE.02:0.90 MOVE.04:0.08"},
	{Base: "帰る", Spec: "MOVE.03:0.92 EXIST.05:0.05 MOVE.01:0.03"},
	{Base: "到着する", Spec: "MOVE.04:0.94"},
	{Base: "着く", Spec: "MOVE.04:0.90 MOVE.02:0.06"},
	{Base: "出発する", Spec: "MOVE.05:0.94"},
	{Base: "出る", Spec: "MOVE.13:0.62 MOVE.05:0.22 CHANGE.08:0.10"},
	{Base: "入る", Spec: "MOVE.12:0.88 WORK.01:0.06 EXIST.02:0.04"},
	{Base: "退く", Spec: "MOVE.13:0.70 MOVE.05:0.24"},
	{Base: "歩く", Spec: "MOVE.06:0.84 RUN.01:0.12"},
	{Base: "走る", Spec: "RUN.01:0.86 MOVE.06:0.10 RUN.05:0.03"},
	{Base: "駆ける", Spec: "RUN.01:0.82 MOVE.05:0.14"},
	{Base: "飛ぶ", Spec: "MOVE.15:0.88 MOVE.01:0.08"},
	{Base: "運ぶ", Spec: "MOVE.07:0.90 TRANSFER.10:0.07"},
	{Base: "持っていく", Spec: "MOVE.08:0.84 MOVE.07:0.12"},
	{Base: "持ってくる", Spec: "MOVE.08:0.86 TRANSFER.10:0.10"},
	{Base: "取る", Spec: "MOVE.09:0.38 TRANSFER.09:0.22 PERCEIVE.07:0.18 CONSUME.01:0.08"},
	{Base: "撮る", Spec: "PERCEIVE.01:0.60 WORK.07:0.20 MOVE.09:0.16"},
	{Base: "受け取る", Spec: "TRANSFER.09:0.90 MOVE.09:0.06"},
	{Base: "取りに行く", Spec: "MOVE.10:0.82 MOVE.09:0.12"},
	{Base: "ついていく", Spec: "MOVE.11:0.88"},
	{Base: "従う", Spec: "MOVE.11:0.50 WORK.01:0.28 WORK.06:0.14"},
	{Base: "追う", Spec: "MOVE.11:0.84 PERCEIVE.07:0.08"},
	{Base: "逃げる", Spec: "MOVE.17:0.86 MOVE.05:0.08"},
	{Base: "近づく", Spec: "MOVE.18:0.90"},
	{Base: "寄る", Spec: "MOVE.18:0.54 MEET.02:0.28 MOVE.05:0.14"},
	{Base: "移る", Spec: "MOVE.01:0.52 CHANGE.06:0.26 MOVE.03:0.18"},
	{Base: "出国する", Spec: "MOVE.05:0.92 MOVE.13:0.06"},
	{Base: "渡る", Spec: "MOVE.12:0.40 MOVE.01:0.44 RUN.05:0.12"},
	{Base: "泳ぐ", Spec: "MOVE.06:0.55 MOVE.14:0.38"},
	{Base: "登る", Spec: "MOVE.01:0.70 MOVE.18:0.24"},
	{Base: "降りる", Spec: "MOVE.13:0.72 MOVE.05:0.22"},
	{Base: "渡す", Spec: "TRANSFER.01:0.92 TRANSFER.14:0.06"},
	{Base: "あげる", Spec: "TRANSFER.01:0.66 TRANSFER.07:0.16 HAVE.07:0.06"},
	{Base: "くれる", Spec: "TRANSFER.01:0.88 TRANSFER.07:0.08"},
	{Base: "送る", Spec: "TRANSFER.02:0.90 MOVE.08:0.06"},
	{Base: "届ける", Spec: "TRANSFER.10:0.90 TRANSFER.02:0.08"},
	{Base: "貸す", Spec: "TRANSFER.03:0.92"},
	{Base: "借りる", Spec: "TRANSFER.04:0.92"},
	{Base: "買う", Spec: "TRANSFER.05:0.93"},
	{Base: "売る", Spec: "TRANSFER.06:0.93"},
	{Base: "見せる", Spec: "TRANSFER.08:0.88 PERCEIVE.02:0.08"},
	{Base: "出す", Spec: "TRANSFER.10:0.30 MOVE.09:0.26 TRANSFER.15:0.20 CONSUME.01:0.14"},
	{Base: "配る", Spec: "TRANSFER.11:0.90"},
	{Base: "交換する", Spec: "TRANSFER.12:0.93"},
	{Base: "盗む", Spec: "TRANSFER.13:0.91 MOVE.09:0.06"},
	{Base: "手放す", Spec: "TRANSFER.01:0.55 HAVE.05:0.30 MOVE.09:0.10"},
}

// jaTableB: speech acts and cognitive states.
var jaTableB = []entry{
	{Base: "言う", Spec: "COMMUNICATE.01:0.88 COMMUNICATE.02:0.08"},
	{Base: "話す", Spec: "COMMUNICATE.06:0.72 COMMUNICATE.02:0.16 MOVE.08:0.08"},
	{Base: "喋る", Spec: "COMMUNICATE.06:0.88"},
	{Base: "しゃべる", Spec: "COMMUNICATE.06:0.86"},
	{Base: "伝える", Spec: "COMMUNICATE.02:0.86 COMMUNICATE.01:0.10"},
	{Base: "質問する", Spec: "COMMUNICATE.03:0.90"},
	{Base: "尋ねる", Spec: "COMMUNICATE.03:0.86"},
	{Base: "聞く", Spec: "PERCEIVE.03:0.62 COMMUNICATE.03:0.28"},
	{Base: "答える", Spec: "COMMUNICATE.04:0.90"},
	{Base: "返答する", Spec: "COMMUNICATE.04:0.90"},
	{Base: "説明する", Spec: "COMMUNICATE.05:0.92"},
	{Base: "書く", Spec: "COMMUNICATE.07:0.72 WORK.07:0.20"},
	{Base: "描く", Spec: "COMMUNICATE.07:0.36 WORK.07:0.44"},
	{Base: "電話する", Spec: "COMMUNICATE.08:0.90"},
	{Base: "呼ぶ", Spec: "COMMUNICATE.08:0.50 MEET.03:0.22 WORK.02:0.16"},
	{Base: "名づける", Spec: "COMMUNICATE.09:0.90"},
	{Base: "怒鳴る", Spec: "COMMUNICATE.10:0.92"},
	{Base: "ささやぐ", Spec: "COMMUNICATE.11:0.92"},
	{Base: "約束する", Spec: "COMMUNICATE.12:0.92"},
	{Base: "忠告する", Spec: "COMMUNICATE.13:0.90"},
	{Base: "謝る", Spec: "COMMUNICATE.14:0.92"},
	{Base: "詫びる", Spec: "COMMUNICATE.14:0.90"},
	// WORK.04 is READ, which is what a verb with a を-object means far more
	// often than "see". PERCEIVE.01 led the table before and won by weight, so
	// 「本を読んだ」 came out as "saw a book" even though the construction for
	// READ existed and was unreachable.
	{Base: "読む", Spec: "WORK.04:0.94 MENTAL.11:0.04 PERCEIVE.01:0.02"},
	{Base: "報告する", Spec: "COMMUNICATE.02:0.88"},
	{Base: "通知する", Spec: "COMMUNICATE.02:0.88"},
	// する is the most frequent verb in the language and it was missing. The
	// corpus diagnostic is what made that visible: it reported する as an
	// unknown lexeme three times, and する is not literary, it is not rare, and
	// no table of Japanese verbs should lack it.
	//
	// The readings are deliberately few and weighted low. する is a light verb
	// and its real sense is supplied by what it attaches to.
	//
	// The ordering encodes one rule: a reading whose required arguments the
	// clause can actually supply outranks one whose it cannot. CHANGE.02 and
	// CHANGE.06 both require a comitative, so 「肥料をやりとりする」 — which has
	// an object and nothing else — could never satisfy them, and choosing them
	// on weight alone produced a sentence reported as missing a comitative that
	// Japanese never wrote. CHANGE.08 and EXIST.02 require only a theme, which
	// is what a light verb with one argument can fill. The なる readings stay
	// in the list because when an adjective is present they are the right ones,
	// and by then the comitative is there.
	//
	// An unlisted compound verb — 勉強する, 到着する — is still unknown, and
	// reporting that is correct; claiming coverage here would not be.
	{Base: "する", Spec: "CHANGE.08:0.38 EXIST.02:0.28 CHANGE.02:0.18 CHANGE.06:0.12"},
	// 為る is SudachiDict's lemma for する, and the lookup tries the lemma
	// before the surface — so listing する alone never matched under the
	// backend that reports lemmas. The previous commit listed surface forms
	// only, and would have looked like a closed gap that had changed nothing.
	{Base: "為る", Spec: "CHANGE.08:0.38 EXIST.02:0.28 CHANGE.02:0.18 CHANGE.06:0.12"},
	{Base: "為た", Spec: "CHANGE.08:0.38 EXIST.02:0.28 CHANGE.02:0.18 CHANGE.06:0.12"},
	{Base: "為ている", Spec: "CHANGE.08:0.36 EXIST.02:0.26 CHANGE.02:0.18 CHANGE.06:0.12"},
	{Base: "した", Spec: "CHANGE.08:0.38 EXIST.02:0.28 CHANGE.02:0.18 CHANGE.06:0.12"},
	{Base: "してる", Spec: "CHANGE.08:0.36 EXIST.02:0.26 CHANGE.02:0.18 CHANGE.06:0.12"},
	// 来る is the second most basic verb in the language and was missing. Its
	// direction is contrastive — that is the whole difference between 来る and
	// 行く — so it cannot be folded into a generic motion sense.
	{Base: "来る", Spec: "MOVE.02:0.88 MOVE.14:0.06"},
	{Base: "来た", Spec: "MOVE.02:0.82 MOVE.14:0.08"},
	{Base: "きて", Spec: "MOVE.02:0.82 MOVE.14:0.08"},
	{Base: "思う", Spec: "MENTAL.01:0.66 MENTAL.03:0.20 MENTAL.07:0.10"},
	{Base: "考える", Spec: "MENTAL.01:0.56 MENTAL.13:0.26 MENTAL.09:0.14"},
	{Base: "知る", Spec: "MENTAL.02:0.90"},
	{Base: "分かる", Spec: "MENTAL.11:0.82 MENTAL.02:0.16"},
	{Base: "信じる", Spec: "MENTAL.03:0.90"},
	{Base: "推測する", Spec: "MENTAL.04:0.90"},
	{Base: "忘れる", Spec: "MENTAL.05:0.92"},
	{Base: "覚える", Spec: "MENTAL.06:0.70 WORK.04:0.26"},
	{Base: "思い出す", Spec: "MENTAL.06:0.92"},
	{Base: "欲しい", Spec: "MENTAL.07:0.90"},
	{Base: "望む", Spec: "MENTAL.07:0.86"},
	{Base: "決定する", Spec: "MENTAL.08:0.90"},
	{Base: "決める", Spec: "MENTAL.08:0.90"},
	{Base: "計画する", Spec: "MENTAL.09:0.90"},
	{Base: "意味する", Spec: "MENTAL.10:0.90"},
	{Base: "理解する", Spec: "MENTAL.11:0.90"},
	{Base: "疑う", Spec: "MENTAL.12:0.86"},
	{Base: "検討する", Spec: "MENTAL.13:0.86"},
}

// jaTableC: affect, perception, existence, possession and the copula.
var jaTableC = []entry{
	{Base: "好き", Spec: "FEEL.01:0.92"},
	{Base: "嫌", Spec: "FEEL.03:0.88"},
	{Base: "嫌い", Spec: "FEEL.03:0.90"},
	{Base: "優しい", Spec: "FEEL.01:0.60 FEEL.11:0.28"},
	{Base: "愛する", Spec: "FEEL.02:0.92"},
	{Base: "嫌う", Spec: "FEEL.03:0.90"},
	{Base: "怖い", Spec: "FEEL.04:0.90"},
	{Base: "喜ぶ", Spec: "FEEL.05:0.90"},
	{Base: "嬉しい", Spec: "FEEL.07:0.84 FEEL.05:0.14"},
	{Base: "悲しい", Spec: "FEEL.08:0.92"},
	{Base: "悔しい", Spec: "FEEL.09:0.80 FEEL.08:0.18"},
	{Base: "怒る", Spec: "FEEL.09:0.92"},
	{Base: "驚く", Spec: "FEEL.10:0.90"},
	{Base: "残念", Spec: "FEEL.06:0.90"},
	{Base: "心配", Spec: "FEEL.08:0.40 MENTAL.07:0.30 MENTAL.13:0.24"},
	{Base: "気を使う", Spec: "FEEL.11:0.88"},
	{Base: "見る", Spec: "PERCEIVE.01:0.56 PERCEIVE.02:0.20 MEET.01:0.14 WORK.01:0.06"},
	{Base: "観る", Spec: "PERCEIVE.01:0.62 MENTAL.11:0.20"},
	{Base: "見つける", Spec: "PERCEIVE.07:0.80 PERCEIVE.01:0.18"},
	{Base: "目に入る", Spec: "PERCEIVE.06:0.84 PERCEIVE.01:0.14"},
	{Base: "目が利く", Spec: "PERCEIVE.11:0.90"},
	{Base: "気づく", Spec: "PERCEIVE.06:0.90"},
	{Base: "耳にする", Spec: "PERCEIVE.03:0.90"},
	{Base: "眺める", Spec: "PERCEIVE.05:0.72 PERCEIVE.02:0.26"},
	{Base: "匂う", Spec: "PERCEIVE.08:0.84"},
	{Base: "触る", Spec: "PERCEIVE.09:0.78 MOVE.09:0.18"},
	{Base: "見分ける", Spec: "PERCEIVE.10:0.72 PERCEIVE.11:0.26"},
	// Polite forms are indexed explicitly. Deleting the duplicated
	// conjugation engine in internal/lexicon left the table holding base forms
	// only, which is accurate but fatal in practice: です/ます/ました/まして are
	// the forms almost every ordinary Japanese sentence actually uses, so the
	// copula and light verbs were unreachable and every polite sentence died as
	// UNKNOWN.VERB with a perfectly good morphological analysis behind it.
	{Base: "です", Spec: "COPULA.03:0.92"},
	{Base: "ですね", Spec: "COPULA.03:0.92"},
	// The plain copula and the written formal one. です/でした were here and
	// these were not, which is backwards: だ is the more frequent of the two and
	// it is what most of written and spoken Japanese uses. Every 「〜である」
	// and 「〜だ」 sentence was reported as an auxiliary head with no
	// predicate.
	{Base: "だ", Spec: "COPULA.01:0.92"},
	{Base: "である", Spec: "COPULA.04:0.94"},
	{Base: "であった", Spec: "COPULA.04:0.70 COPULA.02:0.24"},
	{Base: "ですが", Spec: "COPULA.03:0.80 COPULA.05:0.14"},
	{Base: "でした", Spec: "COPULA.02:0.92"},
	{Base: "では", Spec: "COPULA.03:0.70"},
	{Base: "ます", Spec: "COPULA.03:0.60 EXIST.02:0.20"},
	{Base: "ました", Spec: "COPULA.02:0.60"},
	{Base: "まして", Spec: "COPULA.03:0.70"},
	{Base: "ません", Spec: "COPULA.03:0.62"},
	{Base: "ませんでした", Spec: "COPULA.02:0.62"},
	{Base: "ましょう", Spec: "COPULA.03:0.60"},
	{Base: "ますか", Spec: "COPULA.03:0.70"},
	{Base: "ませんで", Spec: "COPULA.03:0.58"},
	{Base: "だっ", Spec: "COPULA.02:0.90"},
	{Base: "ならば", Spec: "COPULA.03:0.60"},
	{Base: "でしょう", Spec: "COPULA.05:0.86 COPULA.03:0.12"},
	{Base: "だ", Spec: "COPULA.01:0.92"},
	{Base: "である", Spec: "COPULA.04:0.90"},
	{Base: "です", Spec: "COPULA.03:0.92"},
	{Base: "だった", Spec: "COPULA.02:0.92"},
	{Base: "でしょう", Spec: "COPULA.05:0.86 COPULA.03:0.12"},
	{Base: "いる", Spec: "EXIST.02:0.60 HAVE.01:0.22 SLEEP.03:0.10"},
	{Base: "ある", Spec: "EXIST.02:0.70 HAVE.04:0.18 HAVE.01:0.08"},
	{Base: "いない", Spec: "EXIST.09:0.90"},
	{Base: "ない", Spec: "EXIST.09:0.54 MENTAL.05:0.20 HAVE.05:0.18"},
	{Base: "なる", Spec: "CHANGE.06:0.68 EXIST.05:0.18 EXIST.02:0.10"},
	{Base: "生きる", Spec: "EXIST.02:0.48 EXIST.08:0.34"},
	{Base: "住む", Spec: "EXIST.08:0.90"},
	{Base: "生まれる", Spec: "EXIST.06:0.92"},
	{Base: "死ぬ", Spec: "EXIST.07:0.92"},
	{Base: "残す", Spec: "EXIST.05:0.72 MOVE.09:0.18"},
	{Base: "残る", Spec: "EXIST.05:0.86 EXIST.02:0.10"},
	{Base: "ように見える", Spec: "EXIST.03:0.88"},
	{Base: "でいる", Spec: "EXIST.05:0.86"},
	{Base: "持つ", Spec: "HAVE.01:0.62 HAVE.06:0.22 HAVE.02:0.12"},
	{Base: "持ってる", Spec: "HAVE.01:0.78"},
	{Base: "所有する", Spec: "HAVE.02:0.90"},
	{Base: "含む", Spec: "HAVE.04:0.86 EXIST.10:0.10"},
	{Base: "詰まってる", Spec: "HAVE.04:0.80"},
	{Base: "欠く", Spec: "HAVE.05:0.90"},
	{Base: "足りない", Spec: "HAVE.05:0.90"},
	{Base: "着る", Spec: "HAVE.07:0.86"},
	{Base: "備える", Spec: "HAVE.08:0.84 HAVE.01:0.12"},
}

// jaTableD: comparison, quantification, modality and change of state.
var jaTableD = []entry{
	{Base: "多い", Spec: "QUANTIFY.01:0.88 COMPARE.01:0.08"},
	{Base: "少ない", Spec: "QUANTIFY.03:0.86 COMPARE.02:0.10"},
	{Base: "大きい", Spec: "COMPARE.01:0.62 QUANTIFY.01:0.18"},
	{Base: "小さい", Spec: "COMPARE.02:0.62 QUANTIFY.03:0.18"},
	{Base: "良い", Spec: "COMPARE.03:0.86 EXIST.03:0.10"},
	{Base: "悪い", Spec: "COMPARE.04:0.84"},
	{Base: "同じ", Spec: "COMPARE.08:0.90"},
	{Base: "違う", Spec: "COMPARE.06:0.88"},
	{Base: "安い", Spec: "COMPARE.02:0.52 TRANSFER.05:0.24"},
	{Base: "高い", Spec: "COMPARE.01:0.48 TRANSFER.05:0.26"},
	{Base: "すべて", Spec: "QUANTIFY.04:0.90"},
	{Base: "全部", Spec: "QUANTIFY.04:0.88"},
	{Base: "皆", Spec: "QUANTIFY.04:0.88 QUANTIFY.07:0.06"},
	{Base: "みんな", Spec: "QUANTIFY.04:0.84 QUANTIFY.07:0.10"},
	{Base: "全員", Spec: "QUANTIFY.07:0.92"},
	{Base: "誰も", Spec: "QUANTIFY.09:0.92"},
	{Base: "誰か", Spec: "QUANTIFY.05:0.92"},
	{Base: "いくつか", Spec: "QUANTIFY.05:0.72 QUANTIFY.08:0.24"},
	{Base: "両方", Spec: "QUANTIFY.10:0.92"},
	{Base: "たくさん", Spec: "QUANTIFY.01:0.88"},
	{Base: "少し", Spec: "QUANTIFY.03:0.86"},
	{Base: "一番", Spec: "QUANTIFY.06:0.88 COMPARE.01:0.06"},
	{Base: "ほとんど", Spec: "QUANTIFY.06:0.88"},
	{Base: "必ず", Spec: "MODAL.01:0.80 MODAL.03:0.12"},
	{Base: "しなければならない", Spec: "MODAL.01:0.92"},
	{Base: "べき", Spec: "MODAL.02:0.88"},
	{Base: "てもいい", Spec: "MODAL.05:0.88"},
	{Base: "てもいけない", Spec: "MODAL.07:0.92"},
	{Base: "ことができる", Spec: "MODAL.06:0.86 MODAL.03:0.08"},
	{Base: "かもしれない", Spec: "MODAL.03:0.90"},
	{Base: "変わる", Spec: "CHANGE.01:0.90"},
	{Base: "変になる", Spec: "CHANGE.01:0.86"},
	{Base: "成長する", Spec: "CHANGE.03:0.90"},
	{Base: "増える", Spec: "CHANGE.04:0.90"},
	{Base: "減る", Spec: "CHANGE.05:0.90"},
	{Base: "発展する", Spec: "CHANGE.07:0.88"},
	{Base: "起こる", Spec: "CHANGE.08:0.88 CHANGE.06:0.06"},
	{Base: "起きる", Spec: "CHANGE.08:0.54 SLEEP.02:0.34"},
	{Base: "進歩する", Spec: "CHANGE.07:0.90"},
}

// jaTableE: ingestion, weather, temporal reference, social contact, work and
// rest.
var jaTableE = []entry{
	{Base: "食べる", Spec: "CONSUME.01:0.92"},
	{Base: "飲む", Spec: "CONSUME.02:0.92"},
	{Base: "味わう", Spec: "CONSUME.03:0.86 FEEL.01:0.10"},
	{Base: "料理する", Spec: "CONSUME.06:0.90"},
	{Base: "作る", Spec: "WORK.07:0.88"},
	{Base: "降る", Spec: "WEATHER.01:0.54 WEATHER.02:0.40"},
	{Base: "雨が降る", Spec: "WEATHER.01:0.92"},
	{Base: "雪が降る", Spec: "WEATHER.02:0.92"},
	{Base: "晴れる", Spec: "WEATHER.03:0.62 WEATHER.10:0.32"},
	{Base: "曇る", Spec: "WEATHER.04:0.90"},
	{Base: "寒くなる", Spec: "WEATHER.05:0.84 CHANGE.06:0.10"},
	{Base: "暑くなる", Spec: "WEATHER.06:0.84 CHANGE.06:0.10"},
	{Base: "暴れる", Spec: "WEATHER.09:0.88"},
	{Base: "前", Spec: "TIME.01:0.84 TIME.07:0.10"},
	{Base: "後", Spec: "TIME.02:0.84 TIME.07:0.10"},
	{Base: "間", Spec: "TIME.07:0.90"},
	{Base: " 동안", Spec: "TIME.07:0.92"},
	{Base: "始める", Spec: "TIME.04:0.88 CHANGE.06:0.08"},
	{Base: "終える", Spec: "TIME.05:0.88"},
	{Base: "終わる", Spec: "TIME.05:0.92 TIME.03:0.04"},
	{Base: "続く", Spec: "TIME.03:0.78 EXIST.05:0.16"},
	{Base: "去年", Spec: "TIME.01:0.70 TIME.03:0.24"},
	{Base: "明日", Spec: "TIME.02:0.72"},
	{Base: "昨日", Spec: "TIME.01:0.76"},
	{Base: "今朝", Spec: "TIME.01:0.70"},
	{Base: "来年", Spec: "TIME.02:0.74"},
	{Base: "今年", Spec: "TIME.07:0.72"},
	{Base: "朝", Spec: "TIME.07:0.76"},
	{Base: "夜", Spec: "TIME.07:0.76"},
	{Base: "夕方", Spec: "TIME.07:0.76"},
	{Base: "毎朝", Spec: "QUANTIFY.07:0.80 TIME.07:0.14"},
	{Base: "毎日", Spec: "QUANTIFY.07:0.76 TIME.07:0.18"},
	{Base: "今日", Spec: "TIME.07:0.74 TIME.01:0.18"},
	{Base: "すぐ", Spec: "TIME.08:0.84"},
	{Base: "もう", Spec: "TIME.08:0.80"},
	{Base: "まだ", Spec: "TIME.01:0.72"},
	{Base: "会う", Spec: "MEET.01:0.88"},
	{Base: "訪問する", Spec: "MEET.02:0.90"},
	{Base: "訪ねる", Spec: "MEET.02:0.88"},
	{Base: "挨拶する", Spec: "MEET.03:0.90"},
	{Base: "見送る", Spec: "MEET.04:0.90"},
	{Base: "出会う", Spec: "MEET.05:0.86 PERCEIVE.07:0.08"},
	{Base: "迎える", Spec: "MEET.06:0.88"},
	{Base: "紹介する", Spec: "MEET.07:0.90"},
	{Base: "働く", Spec: "WORK.01:0.90"},
	{Base: "勉強する", Spec: "WORK.02:0.88 WORK.04:0.08"},
	{Base: "教える", Spec: "WORK.03:0.90"},
	{Base: "学ぶ", Spec: "WORK.04:0.90"},
	{Base: "習う", Spec: "WORK.04:0.88 WORK.02:0.08"},
	{Base: "動かす", Spec: "RUN.02:0.82 WORK.05:0.14"},
	{Base: "運営する", Spec: "RUN.03:0.88 WORK.06:0.08"},
	{Base: "稼働する", Spec: "RUN.04:0.90"},
	{Base: "修理する", Spec: "WORK.08:0.90"},
	{Base: "使う", Spec: "WORK.09:0.88"},
	{Base: "寝る", Spec: "SLEEP.01:0.90"},
	{Base: "眠る", Spec: "SLEEP.01:0.88"},
	{Base: "休む", Spec: "SLEEP.03:0.86 EXIST.05:0.08"},
	// 疲れる is e-row: the te-form drops the る (疲れて, 疲れた).
	{Base: "疲れる", Forms: []string{"疲れて", "疲れた", "疲れてる", "疲れます", "疲れました", "疲れない", "疲しなかった"}, Spec: "SLEEP.04:0.90"},
}

// jaTables is the assembled Japanese table. Only surfaces that reach a
// predicate belong here: pronouns, conjunctions and adverbs have no sense of
// their own and belong to the parser, not to the ontology.
var jaTables = [][]entry{
	jaTableA, jaTableB, jaTableC, jaTableD, jaTableE,
}
