package lexicon

// English surface data.
//
// Rows are keyed by lemma; the regular inflection generator (enForms) plus the
// explicit Forms lists and the irregular table below cover the inflected forms,
// so a caller may pass either. Weight is a prior, not a decision: run keeps
// every RUN_* reading (plan.md §10), see keeps both seeing and meeting, get
// keeps receiving, becoming and obtaining, break keeps breaking, breaking and
// a broken distribution.

var enIrregular = []struct {
	Base  string
	Forms []string
}{
	{Base: "be", Forms: []string{"am", "is", "are", "was", "were", "been", "being"}},
	{Base: "have", Forms: []string{"has", "had", "having"}},
	{Base: "do", Forms: []string{"does", "did", "done", "doing"}},
	{Base: "go", Forms: []string{"goes", "went", "gone", "going"}},
	{Base: "come", Forms: []string{"comes", "came", "coming"}},
	{Base: "return", Forms: []string{"returns", "returned", "returning"}},
	{Base: "leave", Forms: []string{"leaves", "left", "leaving"}},
	{Base: "meet", Forms: []string{"meets", "met", "meeting"}},
	{Base: "say", Forms: []string{"says", "said", "saying"}},
	{Base: "tell", Forms: []string{"tells", "told", "telling"}},
	{Base: "speak", Forms: []string{"speaks", "spoke", "spoken", "speaking"}},
	{Base: "give", Forms: []string{"gives", "gave", "given", "giving"}},
	{Base: "take", Forms: []string{"takes", "took", "taken", "taking"}},
	{Base: "get", Forms: []string{"gets", "got", "gotten", "getting"}},
	{Base: "make", Forms: []string{"makes", "made", "making"}},
	{Base: "buy", Forms: []string{"buys", "bought", "buying"}},
	{Base: "bring", Forms: []string{"brings", "brought", "bringing"}},
	{Base: "think", Forms: []string{"thinks", "thought", "thinking"}},
	{Base: "know", Forms: []string{"knows", "knew", "known", "knowing"}},
	{Base: "find", Forms: []string{"finds", "found", "finding"}},
	{Base: "see", Forms: []string{"sees", "saw", "seen", "seeing"}},
	{Base: "hear", Forms: []string{"hears", "heard", "hearing"}},
	{Base: "feel", Forms: []string{"feels", "felt", "feeling"}},
	{Base: "keep", Forms: []string{"keeps", "kept", "keeping"}},
	{Base: "send", Forms: []string{"sends", "sent", "sending"}},
	{Base: "build", Forms: []string{"builds", "built", "building"}},
	{Base: "hold", Forms: []string{"holds", "held", "holding"}},
	{Base: "read", Forms: []string{"reads", "reading"}},
	{Base: "write", Forms: []string{"writes", "wrote", "written", "writing"}},
	{Base: "run", Forms: []string{"runs", "ran", "running"}},
	{Base: "fly", Forms: []string{"flies", "flew", "flown", "flying"}},
	{Base: "eat", Forms: []string{"eats", "ate", "eaten", "eating"}},
	{Base: "drink", Forms: []string{"drinks", "drank", "drunk", "drinking"}},
	{Base: "sleep", Forms: []string{"sleeps", "slept", "sleeping"}},
	{Base: "break", Forms: []string{"breaks", "broke", "broken", "breaking"}},
	{Base: "light", Forms: []string{"lights", "lit", "lighting"}},
	{Base: "begin", Forms: []string{"begins", "began", "begun", "beginning"}},
	{Base: "become", Forms: []string{"becomes", "became", "becoming"}},
	{Base: "grow", Forms: []string{"grows", "grew", "grown", "growing"}},
	{Base: "throw", Forms: []string{"throws", "threw", "thrown", "throwing"}},
	{Base: "catch", Forms: []string{"catches", "caught", "catching"}},
	{Base: "teach", Forms: []string{"teaches", "taught", "teaching"}},
	{Base: "sell", Forms: []string{"sells", "sold", "selling"}},
	{Base: "lend", Forms: []string{"lends", "lent", "lending"}},
	{Base: "borrow", Forms: []string{"borrows", "borrowed", "borrowing"}},
	{Base: "show", Forms: []string{"shows", "showed", "shown", "showing"}},
	{Base: "swim", Forms: []string{"swims", "swam", "swum", "swimming"}},
	{Base: "sing", Forms: []string{"sings", "sang", "sung", "singing"}},
	{Base: "lose", Forms: []string{"loses", "lost", "losing"}},
	{Base: "pay", Forms: []string{"pays", "paid", "paying"}},
	{Base: "put", Forms: []string{"puts", "putting"}},
	{Base: "cut", Forms: []string{"cuts", "cutting"}},
	{Base: "let", Forms: []string{"lets", "letting"}},
	{Base: "set", Forms: []string{"sets", "setting"}},
	{Base: "sit", Forms: []string{"sits", "sat", "sitting"}},
	{Base: "stand", Forms: []string{"stands", "stood", "standing"}},
	{Base: "spend", Forms: []string{"spends", "spent", "spending"}},
	{Base: "win", Forms: []string{"wins", "won", "winning"}},
	{Base: "forget", Forms: []string{"forgets", "forgot", "forgotten", "forgetting"}},
}

// enTableA: motion, transfer and speech.
var enTableA = []entry{
	{Base: "go", Spec: "MOVE.01:0.86 MOVE.04:0.08 WORK.01:0.06"},
	{Base: "come", Spec: "MOVE.02:0.90 MOVE.04:0.08"},
	{Base: "return", Spec: "MOVE.03:0.90 EXIST.05:0.06"},
	{Base: "back", Spec: "MOVE.03:0.44"},
	{Base: "arrive", Spec: "MOVE.04:0.92"},
	{Base: "depart", Spec: "MOVE.05:0.92"},
	{Base: "leave", Spec: "MOVE.13:0.50 MOVE.05:0.38"},
	{Base: "walk", Spec: "MOVE.06:0.84 RUN.01:0.14"},
	{Base: "run", Spec: "RUN.01:0.62 RUN.02:0.14 RUN.03:0.12 RUN.04:0.07 RUN.05:0.05"},
	{Base: "fly", Spec: "MOVE.15:0.88 MOVE.01:0.06"},
	{Base: "carry", Spec: "MOVE.07:0.88 TRANSFER.10:0.08"},
	{Base: "bring", Spec: "MOVE.08:0.86 TRANSFER.10:0.10"},
	{Base: "take", Spec: "MOVE.09:0.46 TRANSFER.09:0.16 CONSUME.01:0.14 MOVE.07:0.12"},
	{Base: "fetch", Spec: "MOVE.10:0.90"},
	{Base: "follow", Spec: "MOVE.11:0.90"},
	{Base: "enter", Spec: "MOVE.12:0.90"},
	{Base: "travel", Spec: "MOVE.14:0.88 MOVE.01:0.08"},
	{Base: "drive", Spec: "MOVE.16:0.76 WORK.05:0.20"},
	{Base: "escape", Spec: "MOVE.17:0.90"},
	{Base: "approach", Spec: "MOVE.18:0.90"},
	{Base: "give", Spec: "TRANSFER.01:0.92 TRANSFER.14:0.06"},
	{Base: "hand", Spec: "TRANSFER.01:0.52 TRANSFER.15:0.40"},
	{Base: "send", Spec: "TRANSFER.02:0.90 MOVE.08:0.08"},
	{Base: "lend", Spec: "TRANSFER.03:0.92"},
	{Base: "borrow", Spec: "TRANSFER.04:0.90 MOVE.09:0.06"},
	{Base: "buy", Spec: "TRANSFER.05:0.92"},
	{Base: "sell", Spec: "TRANSFER.06:0.92"},
	{Base: "offer", Spec: "TRANSFER.07:0.90"},
	{Base: "show", Spec: "TRANSFER.08:0.86 TRANSFER.14:0.08"},
	{Base: "receive", Spec: "TRANSFER.09:0.90 MOVE.09:0.06"},
	{Base: "deliver", Spec: "TRANSFER.10:0.90"},
	{Base: "distribute", Spec: "TRANSFER.11:0.90"},
	{Base: "exchange", Spec: "TRANSFER.12:0.90"},
	{Base: "steal", Spec: "TRANSFER.13:0.90"},
	{Base: "pass", Spec: "TRANSFER.14:0.66 MOVE.12:0.24"},
	{Base: "say", Spec: "COMMUNICATE.01:0.86 MENTAL.10:0.08"},
	{Base: "tell", Spec: "COMMUNICATE.02:0.88 COMMUNICATE.01:0.08"},
	{Base: "ask", Spec: "COMMUNICATE.03:0.90"},
	{Base: "answer", Spec: "COMMUNICATE.04:0.90"},
	{Base: "explain", Spec: "COMMUNICATE.05:0.92"},
	{Base: "talk", Spec: "COMMUNICATE.06:0.80 WORK.02:0.10"},
	{Base: "speak", Spec: "COMMUNICATE.06:0.84 COMMUNICATE.01:0.12"},
	{Base: "write", Spec: "COMMUNICATE.07:0.78 WORK.07:0.18"},
	{Base: "call", Spec: "COMMUNICATE.08:0.56 MEET.03:0.16 WORK.01:0.14 COMMUNICATE.09:0.10"},
	{Base: "name", Spec: "COMMUNICATE.09:0.72 WORK.01:0.20"},
	{Base: "shout", Spec: "COMMUNICATE.10:0.90"},
	{Base: "whisper", Spec: "COMMUNICATE.11:0.90"},
	{Base: "promise", Spec: "COMMUNICATE.12:0.90"},
	{Base: "advise", Spec: "COMMUNICATE.13:0.90"},
	{Base: "apologize", Spec: "COMMUNICATE.14:0.90"},
	{Base: "report", Spec: "COMMUNICATE.02:0.84"},
	{Base: "read", Spec: "PERCEIVE.01:0.42 MENTAL.11:0.28 WORK.02:0.16 COMMUNICATE.07:0.10"},
}

// enTableB: cognition, affect, perception.
var enTableB = []entry{
	{Base: "think", Spec: "MENTAL.01:0.88 MENTAL.03:0.08"},
	{Base: "know", Spec: "MENTAL.02:0.90"},
	{Base: "believe", Spec: "MENTAL.03:0.90"},
	{Base: "guess", Spec: "MENTAL.04:0.90"},
	{Base: "forget", Spec: "MENTAL.05:0.90"},
	{Base: "remember", Spec: "MENTAL.06:0.90"},
	{Base: "want", Spec: "MENTAL.07:0.88"},
	{Base: "decide", Spec: "MENTAL.08:0.90"},
	{Base: "plan", Spec: "MENTAL.09:0.86 MENTAL.01:0.08"},
	{Base: "mean", Spec: "MENTAL.10:0.90"},
	{Base: "understand", Spec: "MENTAL.11:0.90"},
	{Base: "doubt", Spec: "MENTAL.12:0.90"},
	{Base: "consider", Spec: "MENTAL.13:0.86 MENTAL.01:0.08"},
	{Base: "like", Spec: "FEEL.01:0.84 FEEL.11:0.08"},
	{Base: "love", Spec: "FEEL.02:0.90"},
	{Base: "hate", Spec: "FEEL.03:0.90"},
	{Base: "fear", Spec: "FEEL.04:0.88 FEEL.10:0.06"},
	{Base: "glad", Spec: "FEEL.05:0.88"},
	{Base: "sorry", Spec: "FEEL.06:0.88"},
	{Base: "happy", Spec: "FEEL.07:0.88"},
	{Base: "sad", Spec: "FEEL.08:0.90"},
	{Base: "angry", Spec: "FEEL.09:0.90"},
	{Base: "surprised", Spec: "FEEL.10:0.90"},
	{Base: "see", Spec: "PERCEIVE.01:0.44 MEET.01:0.24 MENTAL.11:0.10 PERCEIVE.07:0.08 PERCEIVE.02:0.06"},
	{Base: "look", Spec: "PERCEIVE.02:0.78 PERCEIVE.01:0.14 EXIST.03:0.04"},
	{Base: "hear", Spec: "PERCEIVE.03:0.88 COMMUNICATE.03:0.06"},
	{Base: "listen", Spec: "PERCEIVE.04:0.90"},
	{Base: "watch", Spec: "PERCEIVE.05:0.88 PERCEIVE.02:0.08"},
	{Base: "notice", Spec: "PERCEIVE.06:0.90"},
	{Base: "find", Spec: "PERCEIVE.07:0.78 PERCEIVE.06:0.10 PERCEIVE.01:0.06"},
	{Base: "smell", Spec: "PERCEIVE.08:0.90"},
	{Base: "touch", Spec: "PERCEIVE.09:0.86 MOVE.09:0.08"},
	{Base: "recognize", Spec: "PERCEIVE.10:0.90"},
	{Base: "feel", Spec: "FEEL.11:0.20 PERCEIVE.09:0.16 SLEEP.04:0.14 PERCEIVE.01:0.12 MENTAL.02:0.10"},
	{Base: "tired", Spec: "SLEEP.04:0.92"},
	{Base: "enjoy", Spec: "FEEL.01:0.76 FEEL.07:0.16"},
	{Base: "wait", Spec: "EXIST.05:0.56 TIME.07:0.34"},
	{Base: "hope", Spec: "MENTAL.07:0.74 MENTAL.03:0.20"},
	{Base: "surprise", Spec: "FEEL.10:0.84 MENTAL.04:0.10"},
}

// enTableC: being, possession, comparison, quantity and modality.
var enTableC = []entry{
	{Base: "be", Spec: "EXIST.01:0.62 COPULA.01:0.22 EXIST.02:0.10"},
	{Base: "exist", Spec: "EXIST.02:0.92"},
	{Base: "seem", Spec: "EXIST.03:0.90"},
	{Base: "appear", Spec: "EXIST.04:0.84 CHANGE.09:0.10"},
	{Base: "remain", Spec: "EXIST.05:0.84 EXIST.02:0.08"},
	{Base: "stay", Spec: "EXIST.05:0.70 MOVE.18:0.20"},
	{Base: "live", Spec: "EXIST.02:0.40 EXIST.08:0.40"},
	{Base: "reside", Spec: "EXIST.08:0.92"},
	{Base: "die", Spec: "EXIST.07:0.92"},
	{Base: "born", Spec: "EXIST.06:0.92"},
	{Base: "consist", Spec: "EXIST.10:0.90"},
	{Base: "have", Spec: "HAVE.01:0.76 HAVE.09:0.10 TRANSFER.10:0.08"},
	{Base: "own", Spec: "HAVE.02:0.90"},
	{Base: "possess", Spec: "HAVE.03:0.90"},
	{Base: "contain", Spec: "HAVE.04:0.88 EXIST.10:0.06"},
	{Base: "lack", Spec: "HAVE.05:0.90"},
	{Base: "hold", Spec: "HAVE.06:0.62 TRANSFER.14:0.24"},
	{Base: "wear", Spec: "HAVE.07:0.90"},
	{Base: "equip", Spec: "HAVE.08:0.90"},
	{Base: "owe", Spec: "HAVE.09:0.90"},
	{Base: "share", Spec: "HAVE.10:0.72 TRANSFER.12:0.20"},
	{Base: "more", Spec: "COMPARE.01:0.72 QUANTIFY.01:0.18"},
	{Base: "less", Spec: "COMPARE.02:0.74 QUANTIFY.03:0.16"},
	{Base: "better", Spec: "COMPARE.03:0.88"},
	{Base: "worse", Spec: "COMPARE.04:0.88"},
	{Base: "equal", Spec: "COMPARE.05:0.90"},
	{Base: "different", Spec: "COMPARE.06:0.90"},
	{Base: "similar", Spec: "COMPARE.07:0.90"},
	{Base: "same", Spec: "COMPARE.08:0.90"},
	{Base: "many", Spec: "QUANTIFY.01:0.90"},
	{Base: "much", Spec: "QUANTIFY.02:0.82 COMPARE.01:0.10"},
	{Base: "few", Spec: "QUANTIFY.03:0.90"},
	{Base: "little", Spec: "QUANTIFY.03:0.70 QUANTIFY.02:0.20"},
	{Base: "all", Spec: "QUANTIFY.04:0.90"},
	{Base: "some", Spec: "QUANTIFY.05:0.90"},
	{Base: "most", Spec: "QUANTIFY.06:0.88"},
	{Base: "every", Spec: "QUANTIFY.07:0.90"},
	{Base: "several", Spec: "QUANTIFY.08:0.90"},
	{Base: "none", Spec: "QUANTIFY.09:0.90"},
	{Base: "both", Spec: "QUANTIFY.10:0.90"},
	{Base: "must", Spec: "MODAL.01:0.88 MODAL.07:0.06"},
	{Base: "should", Spec: "MODAL.02:0.90"},
	{Base: "may", Spec: "MODAL.03:0.84 MODAL.05:0.10"},
	{Base: "might", Spec: "MODAL.03:0.90"},
	{Base: "can", Spec: "MODAL.04:0.82 MODAL.06:0.12 MODAL.05:0.06"},
	{Base: "allowed", Spec: "MODAL.05:0.90"},
	{Base: "able", Spec: "MODAL.06:0.90"},
	{Base: "possible", Spec: "MODAL.03:0.72 MODAL.05:0.20"},
	{Base: "probably", Spec: "MODAL.03:0.84"},
	{Base: "perhaps", Spec: "MODAL.03:0.86"},
}

// enTableD: change of state, ingestion, weather, time, social contact, work,
// rest and artifacts.
var enTableD = []entry{
	{Base: "change", Spec: "CHANGE.01:0.86"},
	{Base: "turn", Spec: "CHANGE.02:0.60 MOVE.02:0.22"},
	{Base: "grow", Spec: "CHANGE.03:0.84 CHANGE.07:0.10"},
	{Base: "increase", Spec: "CHANGE.04:0.90"},
	{Base: "decrease", Spec: "CHANGE.05:0.90"},
	{Base: "become", Spec: "CHANGE.06:0.78 COPULA.03:0.10"},
	{Base: "get", Spec: "CHANGE.06:0.48 TRANSFER.09:0.26 MOVE.09:0.14"},
	{Base: "develop", Spec: "CHANGE.07:0.86 WORK.07:0.08"},
	{Base: "happen", Spec: "CHANGE.08:0.86"},
	{Base: "occur", Spec: "CHANGE.08:0.90"},
	{Base: "eat", Spec: "CONSUME.01:0.92"},
	{Base: "drink", Spec: "CONSUME.02:0.92"},
	{Base: "taste", Spec: "CONSUME.03:0.78 FEEL.01:0.06"},
	{Base: "cook", Spec: "CONSUME.06:0.86 WORK.07:0.08"},
	{Base: "rain", Spec: "WEATHER.01:0.56 WEATHER.02:0.34"},
	{Base: "snow", Spec: "WEATHER.02:0.68 WEATHER.01:0.22"},
	{Base: "sunny", Spec: "WEATHER.03:0.90"},
	{Base: "cloudy", Spec: "WEATHER.04:0.90"},
	{Base: "storm", Spec: "WEATHER.09:0.86"},
	{Base: "before", Spec: "TIME.01:0.78 TIME.04:0.14"},
	{Base: "after", Spec: "TIME.02:0.78 TIME.05:0.14"},
	{Base: "last", Spec: "TIME.03:0.78 COMPARE.03:0.08"},
	{Base: "begin", Spec: "TIME.04:0.86"},
	{Base: "start", Spec: "TIME.04:0.76 MOVE.01:0.12"},
	{Base: "finish", Spec: "TIME.05:0.88"},
	{Base: "end", Spec: "TIME.05:0.72 TIME.03:0.20"},
	{Base: "during", Spec: "TIME.07:0.92"},
	{Base: "while", Spec: "TIME.07:0.90"},
	{Base: "early", Spec: "TIME.08:0.90"},
	{Base: "late", Spec: "TIME.09:0.90"},
	{Base: "yesterday", Spec: "TIME.01:0.74"},
	{Base: "tomorrow", Spec: "TIME.02:0.74"},
	{Base: "today", Spec: "TIME.07:0.80"},
	{Base: "soon", Spec: "TIME.08:0.86"},
	{Base: "already", Spec: "TIME.08:0.82"},
	{Base: "still", Spec: "EXIST.05:0.70 TIME.07:0.22"},
	{Base: "meet", Spec: "MEET.01:0.86 PERCEIVE.07:0.08"},
	{Base: "visit", Spec: "MEET.02:0.90"},
	{Base: "greet", Spec: "MEET.03:0.90"},
	{Base: "welcome", Spec: "MEET.06:0.84"},
	{Base: "introduce", Spec: "MEET.07:0.88 WORK.07:0.06"},
	{Base: "work", Spec: "WORK.01:0.84 RUN.04:0.10"},
	{Base: "study", Spec: "WORK.02:0.86 WORK.04:0.08"},
	{Base: "teach", Spec: "WORK.03:0.90"},
	{Base: "learn", Spec: "WORK.04:0.90"},
	{Base: "operate", Spec: "WORK.05:0.72 RUN.02:0.22"},
	{Base: "manage", Spec: "WORK.06:0.74 RUN.03:0.20"},
	{Base: "produce", Spec: "WORK.07:0.90"},
	{Base: "make", Spec: "WORK.07:0.78 MOVE.09:0.10"},
	{Base: "repair", Spec: "WORK.08:0.90"},
	{Base: "use", Spec: "WORK.09:0.90"},
	{Base: "sleep", Spec: "SLEEP.01:0.90"},
	{Base: "wake", Spec: "SLEEP.02:0.88"},
	{Base: "rest", Spec: "SLEEP.03:0.88"},
	{Base: "lie", Spec: "SLEEP.05:0.72 EXIST.05:0.20"},
	{Base: "light", Spec: "CHANGE.09:0.36 ARTIFACT.01:0.20 WEATHER.03:0.18"},
	{Base: "break", Spec: "CHANGE.01:0.54 MOVE.09:0.20 TRANSFER.14:0.16"},
	{Base: "phone", Spec: "ARTIFACT.01:0.52 COMMUNICATE.08:0.40"},
	{Base: "computer", Spec: "ARTIFACT.01:0.72 WORK.05:0.20"},
	{Base: "car", Spec: "ARTIFACT.03:0.90"},
}

// enTables is the assembled English table.
var enTables = [][]entry{enTableA, enTableB, enTableC, enTableD}

// Idioms are detected before their parts are committed to literal predicates
// (plan.md §49). Literal is the compositional fallback kept alive beside the
// idiomatic reading; Gloss is the minimum context the oracle needs to choose
// between them (plan.md §31). Formal is the register weight in [0,1].
var idioms = []*Idiom{
	{ID: "IDIOM.HEAVY_RAIN", SenseID: "WEATHER.01", Surface: "raining cats and dogs", Literal: "WEATHER.01", Gloss: "it is raining very heavily", Formal: 0.3},
	{ID: "IDIOM.HEAVY_RAIN_JP", SenseID: "WEATHER.02", Surface: "雪に負ける", Literal: "WEATHER.02", Gloss: "snow is so heavy that movement fails", Formal: 0.5, Lang: "ja"},
	{ID: "IDIOM.SNOW_FALLS_HARD", SenseID: "WEATHER.02", Surface: "雪が降り積もる", Literal: "WEATHER.02", Gloss: "snow keeps piling up", Formal: 0.6, Lang: "ja"},
	{ID: "IDIOM.PUT_OUT_HAND", SenseID: "TRANSFER.15", Surface: "手を出す", Literal: "TRANSFER.10", Gloss: "lend a hand, or interfere", Formal: 0.7, Lang: "ja"},
	{ID: "IDIOM.BE_CAREFUL_WITH", SenseID: "FEEL.11", Surface: "気を使う", Literal: "MENTAL.13", Gloss: "be considerate towards someone", Formal: 0.7, Lang: "ja"},
	{ID: "IDIOM.SHARP_EYE", SenseID: "PERCEIVE.11", Surface: "目が利く", Literal: "PERCEIVE.01", Gloss: "have a discerning eye for value", Formal: 0.6, Lang: "ja"},
	{ID: "IDIOM.ELECTRIC_TOOTHBRUSH", SenseID: "ARTIFACT.01", Surface: "電動牙刷", Literal: "ARTIFACT.02", Gloss: "an electric toothbrush, a non-compositional compound", Formal: 0.8, Lang: "ja"},
	{ID: "IDIOM.BITE_THE_BULLET", SenseID: "MODAL.01", Surface: "bite the bullet", Gloss: "force oneself to endure something unpleasant", Formal: 0.6},
	{ID: "IDIOM.BREAK_THE_ICE", SenseID: "MEET.01", Surface: "break the ice", Literal: "MOVE.12", Gloss: "relieve the awkwardness at first contact", Formal: 0.6},
	{ID: "IDIOM.UNDER_THE_WEATHER", SenseID: "SLEEP.04", Surface: "under the weather", Gloss: "unwell, low in energy", Formal: 0.5},
	{ID: "IDIOM.HIT_THE_BOOKS", SenseID: "WORK.02", Surface: "hit the books", Gloss: "study hard", Formal: 0.3},
	{ID: "IDIOM.TAKE_A_BREATH", SenseID: "SLEEP.03", Surface: "take a breath", Literal: "CONSUME.02", Gloss: "breathe, rest briefly", Formal: 0.7},
	{ID: "IDIOM.GIVE_HAND", SenseID: "TRANSFER.15", Surface: "give a hand", Literal: "TRANSFER.01", Gloss: "help someone", Formal: 0.6},
	{ID: "IDIOM.LEND_AN_EAR", SenseID: "PERCEIVE.04", Surface: "lend an ear", Literal: "TRANSFER.03", Gloss: "listen attentively", Formal: 0.6},
	{ID: "IDIOM.COUNT_ON", SenseID: "MENTAL.03", Surface: "count on", Literal: "QUANTIFY.01", Gloss: "rely on someone", Formal: 0.6},
	{ID: "IDIOM.SPILL_THE_BEANS", SenseID: "COMMUNICATE.01", Surface: "spill the beans", Literal: "TRANSFER.10", Gloss: "reveal a secret", Formal: 0.3},
	{ID: "IDIOM.BREAK_A_LEG", SenseID: "CHANGE.01", Surface: "break a leg", Gloss: "good luck", Formal: 0.2},
	{ID: "IDIOM.PULL_SOMEBODY_S_LEG", SenseID: "TRANSFER.13", Surface: "pull somebody's leg", Literal: "MOVE.09", Gloss: "tease someone", Formal: 0.4},
	{ID: "IDIOM.SPOT_OF_BOTHER", SenseID: "MENTAL.13", Surface: "a spot of bother", Gloss: "a small trouble", Formal: 0.4},
	{ID: "IDIOM.ON_AND_OFF", SenseID: "TIME.07", Surface: "on and off", Gloss: "occasionally, intermittently", Formal: 0.5},
	{ID: "IDIOM.FACE_TO_FACE", SenseID: "MEET.01", Surface: "face to face", Literal: "PERCEIVE.02", Gloss: "in person", Formal: 0.7},
	{ID: "IDIOM.ONCE_IN_A_BLUE_MOON", SenseID: "QUANTIFY.08", Surface: "once in a blue moon", Gloss: "very rarely", Formal: 0.4},
	{ID: "IDIOM.PIECE_OF_CAKE", SenseID: "COMPARE.02", Surface: "a piece of cake", Literal: "TRANSFER.01", Gloss: "something very easy", Formal: 0.3},
	{ID: "IDIOM.BREAK_DOWN", SenseID: "CHANGE.01", Surface: "break down", Literal: "CHANGE.01", Gloss: "stop functioning", Formal: 0.7},
	{ID: "IDIOM.GET_HANDS_ON", SenseID: "TRANSFER.09", Surface: "get hands on", Literal: "MOVE.09", Gloss: "obtain possession of", Formal: 0.5},
	{ID: "IDIOM.MAKE_UP_MIND", SenseID: "MENTAL.08", Surface: "make up one's mind", Literal: "WORK.07", Gloss: "decide", Formal: 0.6},
	{ID: "IDIOM.COME_ACROSS", SenseID: "MEET.05", Surface: "come across", Literal: "MOVE.02", Gloss: "meet by chance, or discover", Formal: 0.6},
	{ID: "IDIOM.RUN_OUT_OF", SenseID: "HAVE.05", Surface: "run out of", Literal: "RUN.01", Gloss: "exhaust a supply", Formal: 0.6},
	{ID: "IDIOM.FIGURE_OUT", SenseID: "MENTAL.11", Surface: "figure out", Literal: "CONSUME.03", Gloss: "work out, understand", Formal: 0.5},
	{ID: "IDIOM.TAKE_OFF", SenseID: "MOVE.05", Surface: "take off", Literal: "MOVE.09", Gloss: "leave the ground", Formal: 0.7},
	{ID: "IDIOM.STAY_UP", SenseID: "SLEEP.02", Surface: "stay up", Literal: "SLEEP.01", Gloss: "remain awake", Formal: 0.5},
}

// termTable is the terminology memory of plan.md §52. Source is written in the
// language named by Lang; Preferred is the only accepted target form and
// Forbidden lists renderings the realizer must not produce.
var termTable = []*Term{
	{Source: "電動牙刷", Concept: "electric toothbrush", Preferred: "electric toothbrush", Forbidden: []string{"auto toothbrush"}, Note: "non-compositional compound; the sense is ARTIFACT.01", Lang: "ja"},
	{Source: "機械学習", Concept: "machine learning", Preferred: "machine learning", Forbidden: []string{"mechanical learning", "computer learning"}, Lang: "ja"},
	{Source: "自然言語処理", Concept: "natural language processing", Preferred: "natural language processing", Forbidden: []string{"natural language handling"}, Lang: "ja"},
	{Source: "制約", Concept: "constraint", Preferred: "constraint", Forbidden: []string{"restriction"}, Lang: "ja"},
	{Source: "曖昧さ", Concept: "ambiguity", Preferred: "ambiguity", Forbidden: []string{"vagueness", "fuzziness"}, Lang: "ja"},
	{Source: "検証", Concept: "verification", Preferred: "verification", Forbidden: []string{"validation", "inspection"}, Lang: "ja"},
	{Source: "含意", Concept: "entailment", Preferred: "entailment", Forbidden: []string{"implication"}, Lang: "ja"},
	{Source: "述語", Concept: "predicate", Preferred: "predicate", Forbidden: []string{"prediction"}, Lang: "ja"},
	{Source: "格", Concept: "case", Preferred: "case", Forbidden: []string{"form"}, Lang: "ja"},
	{Source: "助詞", Concept: "case particle", Preferred: "case particle", Forbidden: []string{"postposition"}, Lang: "ja"},
	{Source: "主格", Concept: "nominative", Preferred: "subject", Forbidden: []string{"nominative case"}, Lang: "ja"},
	{Source: "electric toothbrush", Concept: "electric toothbrush", Preferred: "電動歯ブラシ", Forbidden: []string{"kinhashi o Electric"}, Lang: "en"},
	{Source: "machine learning", Concept: "machine learning", Preferred: "機械学習", Forbidden: []string{"機械的学習"}, Lang: "en"},
	{Source: "constraint", Concept: "constraint", Preferred: "制約", Forbidden: []string{"制限"}, Lang: "en"},
	{Source: "ambiguity", Concept: "ambiguity", Preferred: "曖昧さ", Forbidden: []string{"あいまいさ"}, Lang: "en"},
	{Source: "verifier", Concept: "verification component", Preferred: "検証器", Forbidden: []string{"検査器"}, Lang: "en"},
}
